nodes: move HUD node to an internal module
gopro/gopro-lib-node.gl pull request #143
Opened 2020-11-16 15:57 UTC by mbouron-gpsw

2020-11-16 18:13 UTC, cboesch-gpsw commented on ngl-tools/player.c
> -        p->paused ^= 1;
this breaks the pause

2020-11-16 18:13 UTC, cboesch-gpsw commented on ngl-tools/player.c
> +        return toggle_hud();
why return?

2020-11-16 18:14 UTC, cboesch-gpsw commented on ngl-tools/player.c
> +    int scale = dw / ww;
`const` or inline?

2020-11-16 18:15 UTC, cboesch-gpsw commented on ngl-tools/player.c
> +    return ngl_configure(p->ngl, &p->ngl_config);
you can pass `config` directly here

2020-11-16 18:17 UTC, cboesch-gpsw commented on libnodegl/node_hud.c
> +    register_time(s, &priv->measures[LATENCY_TOTAL_GPU], gpu_tdraw);
I think the total of GPU doesn't make much sense anymore as well

2020-11-16 18:19 UTC, cboesch-gpsw commented on libnodegl/api.c
> +    int64_t start_time = s->hud ? ngli_gettime_relative() : 0;
`const`

2020-11-16 18:19 UTC, cboesch-gpsw commented on libnodegl/api.c
> +    s->cpu_update_time = s->hud ? (ngli_gettime_relative() - start_time) : 0;
unnecessary `( )`

2020-11-16 18:21 UTC, cboesch-gpsw commented on libnodegl/api.c
> +        ngli_gtimer_start(s->gpu_timer);
can you move `cpu_start_time` after the GPU calls so that it's not accounted in CPU time? (we want to bench the drawing itself as accurately as possible, enabling the benchmark should be out of that).

2020-11-16 20:19 UTC, mbouron-gpsw commented on ngl-tools/player.c
> -        p->paused ^= 1;
Fixed.

2020-11-16 20:20 UTC, mbouron-gpsw commented on ngl-tools/player.c
> +    int scale = dw / ww;
Inlined.

2020-11-16 20:21 UTC, mbouron-gpsw commented on ngl-tools/player.c
> +        return toggle_hud();
toggle_hud() calls ngl_configure() (which can fail). I realize we also don't return in screenshot(). What do you prefer ?

2020-11-16 20:22 UTC, mbouron-gpsw commented on ngl-tools/player.c
> +    return ngl_configure(p->ngl, &p->ngl_config);
Fixed.

2020-11-16 20:23 UTC, mbouron-gpsw commented on libnodegl/node_hud.c
> +    register_time(s, &priv->measures[LATENCY_TOTAL_GPU], gpu_tdraw);
I can remove it with the GPU update measure, if you are OK with that.

2020-11-16 20:27 UTC, mbouron-gpsw commented on libnodegl/api.c
> +    int64_t start_time = s->hud ? ngli_gettime_relative() : 0;
Fixed.

2020-11-16 20:27 UTC, mbouron-gpsw commented on libnodegl/api.c
> +    s->cpu_update_time = s->hud ? (ngli_gettime_relative() - start_time) : 0;
Fixed.

2020-11-16 20:28 UTC, mbouron-gpsw commented on libnodegl/api.c
> +        ngli_gtimer_start(s->gpu_timer);
Fixed.

2020-11-16 20:57 UTC, cboesch-gpsw commented on ngl-tools/player.c
> +        return toggle_hud();
`return` is probably fine, but then the `break` below is unneeded, so I'd remove it

2020-11-16 20:58 UTC, cboesch-gpsw commented on libnodegl/node_hud.c
> +    register_time(s, &priv->measures[LATENCY_TOTAL_GPU], gpu_tdraw);
No preference on having that in the same commit or another one; since it's already split, it's probably fine to have it in a separate commit.

2020-11-16 21:35 UTC, cboesch-gpsw requested changes

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/api.c
> +    struct ngl_config *config = &s->config;
can be `const`

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/api.c
> +
Note: having the HUD positioned here is actually interesting for future improvement: we could have independent measures (visit, prefetch, update), instead of just one.

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/hud.c
> -#define OFFSET(x) offsetof(struct hud_priv, x)
You can probably remove at least `stddef.h` here

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/hud.c
> +    void (*uninit)(struct hud *s, struct widget *widget);
This commit is fairly large; could it be possible to do before this commit:
1. use `struct hud_priv` instead of the `struct ngl_node` first as much as possible
2. rename `struct hud_priv` to `struct hud`

?

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/hud.c
> +    //ngli_bstr_printf(s->csv_line, "\"%f\"", s->last_update_time);
Yes, this one is tricky to deal with...

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/hud.c
> +
No way of having this check earlier? It looks weird to arrive that deep without a scene.

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/hud.c
> +    widgets_make_stats(s);
This function contains a `HACK` related to the order of operations: is it still valid after your changes?

2020-11-16 21:35 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/tests/cmp_resources.py
> -    def _scene_wrap(self, scene):
Can you add a commit to remove the now unused `_scene_wrap` code in `pynodegl-utils/pynodegl_utils/tests/cmp.py`?

2020-11-16 21:35 UTC, cboesch-gpsw commented on libnodegl/api.c
> +        ngli_gctx_query_draw_time(s->gctx, &s->gpu_draw_time);
Doesn't this chunk belongs in a following commit enabling back the drawing of the HUD? Or is it already drawn before this state?

2020-11-16 21:35 UTC, cboesch-gpsw commented on ngl-tools/player.c
> +    case SDLK_h:
This is missing an entry at the end of `doc/ref/ngl-tools/md`

2020-11-16 21:39 UTC, mbouron-gpsw commented on ngl-tools/player.c
> +    case SDLK_h:
Fixed.

2020-11-16 21:49 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/tests/cmp_resources.py
> -    def _scene_wrap(self, scene):
Done.

2020-11-16 21:50 UTC, mbouron-gpsw commented on libnodegl/hud.c
> -#define OFFSET(x) offsetof(struct hud_priv, x)
Done.

2020-11-16 21:52 UTC, mbouron-gpsw commented on libnodegl/api.c
> +    struct ngl_config *config = &s->config;
Done.

2020-11-16 21:54 UTC, mbouron-gpsw commented on libnodegl/api.c
> +        ngli_gctx_query_draw_time(s->gctx, &s->gpu_draw_time);
It belongs to this chunk, the new function ngli_gctx_query_draw_time() must not be called while a renderpass is active.

2020-11-16 21:56 UTC, cboesch-gpsw commented on libnodegl/api.c
> +        ngli_gctx_query_draw_time(s->gctx, &s->gpu_draw_time);
OK

2020-11-16 21:58 UTC, mbouron-gpsw commented on libnodegl/hud.c
> +
I'll check. The HUD should be available even if we don't a scene, IMHO.

2020-11-17 08:09 UTC, mbouron-gpsw commented on libnodegl/hud.c
> +    //ngli_bstr_printf(s->csv_line, "\"%f\"", s->last_update_time);
Fixed.

2020-11-17 08:28 UTC, mbouron-gpsw commented on libnodegl/hud.c
> +    widgets_make_stats(s);
The HACK has already been adjusted to work properly with the new HUD, ie: instead of resetting the draw_count before calling make_stats(), we do it after since ngli_node_draw() is now called before the entier HUD.

2020-11-17 08:58 UTC, mbouron-gpsw commented on ngl-tools/player.c
> +        return toggle_hud();
The break has been removed.

2020-11-17 09:10 UTC, mbouron-gpsw commented on libnodegl/node_hud.c
> +    register_time(s, &priv->measures[LATENCY_TOTAL_GPU], gpu_tdraw);
I've added a separate commit.

2020-11-17 10:37 UTC, mbouron-gpsw commented on libnodegl/hud.c
> +    void (*uninit)(struct hud *s, struct widget *widget);
This branch been rebased on top of your commits that do the split.

2020-11-17 12:36 UTC, cboesch-gpsw approved these changes

2020-11-17 12:48 UTC, merged