Jmoguillansky/meson windows master
gopro/gopro-lib-node.gl pull request #152
Opened 2020-11-25 23:22 UTC by jmoguillansky-gpsw

GL backend working on windows.

Ok:                 209
Expected Fail:      0
Fail:               2

This is still a work in progress.

2020-12-01 08:43 UTC, cboesch-gpsw requested changes

2020-12-01 08:43 UTC, cboesch-gpsw commented on external/scripts/sync.sh
> +OS=$1
- script is missing a shebang
- if posix shell, you want `set -xeu`
- this script is getting changed several times in the history, you need to squash the commits: I had to review that file several times for nothing

2020-12-01 08:43 UTC, cboesch-gpsw commented on external/scripts/sync.sh
> +    cd win64 && tar xzf $TMP_DIR/pkg-config/pkg-config.tgz; cd -
please use a sub-shell instead of `cd ; cd -`

2020-12-01 08:43 UTC, cboesch-gpsw commented on external/scripts/sync.sh
> +    mkdir -p $TMP_DIR/ffmpeg && wget --header "Authorization: token $TOKEN" -nc https://api.github.com/repos/jmoguillansky-gpsw/gopro-pkg/actions/artifacts/28753508/zip -O $TMP_DIR/ffmpeg/ffmpeg_x64-
how long will these artifacts survive?

2020-12-01 08:43 UTC, cboesch-gpsw commented on Makefile
> +#TODO: submit PR for sxplayer changes
can you do that instead? the current branch can't be reviewed until the associated PR is merged in sxplayer

2020-12-01 08:43 UTC, cboesch-gpsw commented on Makefile
> +else
So you are able to run this Makefile? why the external sync script then? you can download from here

2020-12-01 08:43 UTC, cboesch-gpsw commented on Makefile
> +#TODO: identify correct path
what isn't correct?

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +    gbackend_deps += cc.find_library(dep, required: opt_gbackend, dirs: cc_lib_dirs)
I know this is a hack we have in the vulkan branch, but it is incorrect: if we do that, it replaces the search dir, which means the libraries won't be searched on the default paths anymore, so it will likely fail typically in an independent build system.

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  lib_include_dirs += include_directories('..\\external\\win64\\gl\\include')
`..` is incorrect, the builddir could be anywhere: the root makefile is a user of an independently working build system, the dependency doesn't go the other way around.

2020-12-01 08:43 UTC, cboesch-gpsw commented on ngl-tools/meson.build
> +endif
why do you need this?

2020-12-01 08:43 UTC, cboesch-gpsw commented on ngl-tools/meson.build
> +  tool_install_dir = 'Scripts'
"Scripts"? Those are binary programs

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/node_buffer.c
> +    int filesize = ftell(s->fp);
this breaks with large files

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/utils.c
>  int64_t ngli_gettime_relative(void)
This belongs in a dedicated commit, prototype removal is forgotten btw.

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
mmh what's going on here? the commit description needs to explain that

2020-12-01 08:43 UTC, cboesch-gpsw commented on libnodegl/api.c
> +#elif defined(TARGET_WINDOWS)
you can't do that in an isolated commit: it needs to be associated with changes in the `meson.build`, in the CI and in the documentation

2020-12-01 08:43 UTC, cboesch-gpsw commented on ngl-tools/ipc.c
> +#define ssize_t int
why do you define `ssize_t` if you remove it from the code? also, this is defined in mingw, but not msvc apparently

2020-12-01 08:43 UTC, cboesch-gpsw commented on pynodegl/setup.py
> +                self.libraries.append(f[:-4])
This change doesn't belong in `.gitignore` commit

2020-12-01 10:45 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +OS=$1
Thanks I will update...
Regarding the git history I kept two versions of the file but once we sort out the strategy I'll squash the commits.

2020-12-01 10:45 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +    cd win64 && tar xzf $TMP_DIR/pkg-config/pkg-config.tgz; cd -
Thanks, good tip.  I'll update...

2020-12-01 10:48 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +    mkdir -p $TMP_DIR/ffmpeg && wget --header "Authorization: token $TOKEN" -nc https://api.github.com/repos/jmoguillansky-gpsw/gopro-pkg/actions/artifacts/28753508/zip -O $TMP_DIR/ffmpeg/ffmpeg_x64-
3 months, but there's several issues with github action artifacts: 1) require security token, 2) different url for each artifact for each run, thst we don't control.  I think if we decide to host prebuilt binaries we should upload them to an ftp server (via github action)

2020-12-01 10:49 UTC, jmoguillansky-gpsw commented on Makefile
> +#TODO: submit PR for sxplayer changes
Lets discuss the strategy first regarding 3rdparty libs.  If everyone agrees, I'll submit PR

2020-12-01 10:50 UTC, jmoguillansky-gpsw commented on Makefile
> +else
So we can ignore the details / complexity of the main makefile and develop this code in isolation.  We can put this in a gnu makefile format but I think a bash script is simpler?

2020-12-01 10:51 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
>  int64_t ngli_gettime_relative(void)
Thanks I'll update...

2020-12-01 10:53 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
Lots of compile errors if I keep "winapi"... with this change the gl backend works.  Is "winapi" related to symbol visibility and dlls?

2020-12-01 10:56 UTC, jmoguillansky-gpsw commented on ngl-tools/ipc.c
> +#define ssize_t int
It was either define it here or put ifdefs everywhere that recv / send is called and use int on windows and ssize _t on unix.  This was basically a trick to reduce the code changes.  Alternatively we could use macros or abstraction APIs

2020-12-01 10:57 UTC, jmoguillansky-gpsw commented on pynodegl/setup.py
> +                self.libraries.append(f[:-4])
I'll clean up the history...

2020-12-01 11:01 UTC, jmoguillansky-gpsw commented on Makefile
> +#TODO: identify correct path
The sdk path was hardcoded (C:/...)

2020-12-01 11:03 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    gbackend_deps += cc.find_library(dep, required: opt_gbackend, dirs: cc_lib_dirs)
For some reason msvc finds the library but meson doesn't.  I had to add the search paths explicitly.  Alternatively we could just pass the lib names directly as params

2020-12-01 11:04 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  lib_include_dirs += include_directories('..\\external\\win64\\gl\\include')
Meson converts to absolute path.  It actually complained when I tried to pass it an absolute path if I remember correctly

2020-12-01 11:05 UTC, jmoguillansky-gpsw commented on ngl-tools/meson.build
> +endif
I can probably remove it...

2020-12-01 11:06 UTC, jmoguillansky-gpsw commented on ngl-tools/meson.build
> +  tool_install_dir = 'Scripts'
Yes its not the best naming.  When we run python -m venv on windows it sets up a scripts folder but no bin folder.  We can add a folder "bin" but we need to add it to path env variable in the activate script...

2020-12-01 11:07 UTC, jmoguillansky-gpsw commented on libnodegl/node_buffer.c
> +    int filesize = ftell(s->fp);
Will replace with long int

2020-12-01 16:24 UTC, jmoguillansky-gpsw commented on libnodegl/api.c
> +#elif defined(TARGET_WINDOWS)
We should define "NGL_PLATFORM_WINDOWS" if TARGET_WINDOWS.  Not sure if we need two versions: "NGL_PLATFORM_WINDOWS and "NGL_PLATFORM_MINGW"?

2020-12-08 23:59 UTC, jmoguillansky-gpsw commented on Makefile
> +#TODO: submit PR for sxplayer changes
PR submitted

2020-12-12 00:43 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +OS=$1
updated.  Using set -xu

2020-12-12 00:44 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +    cd win64 && tar xzf $TMP_DIR/pkg-config/pkg-config.tgz; cd -
updated

2020-12-12 00:44 UTC, jmoguillansky-gpsw commented on external/scripts/sync.sh
> +    mkdir -p $TMP_DIR/ffmpeg && wget --header "Authorization: token $TOKEN" -nc https://api.github.com/repos/jmoguillansky-gpsw/gopro-pkg/actions/artifacts/28753508/zip -O $TMP_DIR/ffmpeg/ffmpeg_x64-
updated: using binaries from git repo.  They should survive forever

2020-12-12 00:56 UTC, jmoguillansky-gpsw commented on libnodegl/node_buffer.c
> +    int filesize = ftell(s->fp);
already resolved

2020-12-12 00:57 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
>  int64_t ngli_gettime_relative(void)
updated

2020-12-12 00:59 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
This introduced compile errors.  No need to do this

2020-12-12 01:02 UTC, jmoguillansky-gpsw commented on libnodegl/api.c
> +#elif defined(TARGET_WINDOWS)
We have 3 macros:
TARGET_WINDOWS, TARGET_MINGW_W64, and TARGET_MSVC.
For this particular logic, it can be applied to both msvc and mingw (hence TARGET_WINDOWS)
We have the corresponding changes to meson.build and CI.

2020-12-12 01:02 UTC, jmoguillansky-gpsw commented on ngl-tools/ipc.c
> +#define ssize_t int
already resolved

2020-12-12 01:03 UTC, jmoguillansky-gpsw commented on pynodegl/setup.py
> +                self.libraries.append(f[:-4])
updated

2020-12-17 07:54 UTC, jmoguillansky-gpsw commented on .gitattributes
> +* -text
The CI server is converting the line endings (e.g. \n to \r\n) automatically for various files.  I had to disable this

2020-12-17 07:56 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_win.yml
> +          make -j8 TARGET_OS=Windows PKG_CONFIG="D:\\\\a\\\\gopro-lib-node.gl\\\\gopro-lib-node.gl\\\\pkg-config.exe" VCPKG_DIR="D:\\\\a\\\\gopro-lib-node.gl\\\\gopro-lib-node.gl\\\\vcpkg"
can probably use single quotes here instead of lots of escape characters, still learning bash scripting...
https://wiki.bash-hackers.org/

2021-01-04 17:42 UTC, cboesch-gpsw commented on .gitignore
> +/builddir
this looks unrelated

2021-01-04 17:42 UTC, cboesch-gpsw commented on .gitignore
> +external/token.cfg
this is inconsistent and doesn't look like it doesn't belong in this commit but in the one introducing the external w64 stuff

2021-01-04 17:42 UTC, cboesch-gpsw commented on .gitignore
> +/sxplayer*
you can drop that

2021-01-04 17:42 UTC, cboesch-gpsw commented on ngl-tools/meson.build
> +endif
yes but `required` is set to `false` so why is it an issue?

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
Mmh well then, `NGLI_GL_APIENTRY` needs to be drop entirely: it's sole purpose was to work with windows

2021-01-04 17:42 UTC, cboesch-gpsw commented on ngl-tools/meson.build
> +  #TODO: add a bin folder and add it to path in activate script
1. this diff doesn't belong in "nodegl: use TARGET_WINDOWS instead of TARGET_MINGW"
2. cosmetic: please add a space after `#`
3. what is the plan wrt the TODO?

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +	# patch libnodegl.pc TODO: remove
what's your plan for this?

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +	(cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)
if you include `cmd.exe /C` in `ACTIVATE`, does it help getting rid of the condition?

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  message('backend: ' + gbackend_name + ' enabled: ' + all_dep_found.to_string())
`message('backend: @0@ enabled: @1@'.format(gbackend_name, all_dep_found.to_string())` maybe, for consistency with the other messages we have in other `meson.build` files

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +MESON_SETUP_NINJA   = meson setup --backend ninja --prefix="$(W_PREFIX)" --pkg-config-path=$(PREFIX)\\Lib\\pkgconfig -Drpath=true
why is this commit separated from the rest? isn't it needed at the moment windows support is introduced?

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +	(cmd.exe /C $(ACTIVATE) \&\& $(MESON_SETUP) --default-library shared external\\sxplayer builddir\\sxplayer \&\& $(MESON_COMPILE) -C builddir\\sxplayer \&\& $(MESON_INSTALL) -C builddir\\sxplayer)
same here, it looks like you want this squashed into the windows build commit

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/meson.build
> -
same here: i think this belongs in the commit adding windows build support

Note: "update X" is not a good commit message, a commit pretty much always updates something

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  endif
please rebase, this should be available upstream

2021-01-04 17:42 UTC, cboesch-gpsw commented on .gitattributes
> +* -text
please write that in the commit description (and add a "git" prefix to the commit message)

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +	(cmd.exe /C pushd external\\win64\\sdl2_x64-windows \&\& $(PYTHON) scripts/install.py "$(W_PREFIX)" \& popd)
again i think this commit belongs in another

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
> Resolves compile error "No target architecture"

What's going on here? What following include requires `Windows.h` to be included first? Can you add the explanation in the commit description?

Also, we don't mention "bugfix" like this. "utils: fix Windows.h include order" is more consistent with other commits.

2021-01-04 17:42 UTC, cboesch-gpsw commented on libnodegl/log.c
> -#include "config.h"
Aw. We need to merge that one quickly. Please mention in the commit description that it completes the initial attempt in 1494a18c11b2466e3c2c89fa133205bc3ac9be90

2021-01-04 17:42 UTC, cboesch-gpsw commented on Makefile
> +  ifneq ($(shell $(CMD) $(PYTHON) -c "import sys;print(sys.version_info.major)"),$(PYTHON_MAJOR))
again, please squash all of this in the same commit; we don't need to see all your iteration attempts.

2021-01-04 17:42 UTC, cboesch-gpsw commented on .github/workflows/ci_win.yml
> +#          make -j8 tests PYTHON="C:/hostedtoolcache/windows/Python/3.9.0/x64/python.exe" TARGET_OS=Windows
No dead code in the repository please: put that in your personal notes or write a documentation somewhere

2021-01-04 17:42 UTC, cboesch-gpsw commented on .github/workflows/ci_win.yml
> +          wget https://github.com/jmoguillansky-gpsw/gopro-pkg/blob/master/external/win64/pkg-config.exe?raw=true -O pkg-config.exe
can we have something more official that this?

2021-01-04 17:58 UTC, jmoguillansky-gpsw commented on ngl-tools/meson.build
> +endif
it also makes it more clear to the developer which libraries are required for different platforms.  
I can remove this change if you prefer.

2021-01-04 18:05 UTC, jmoguillansky-gpsw commented on ngl-tools/meson.build
> +  #TODO: add a bin folder and add it to path in activate script
3: We can post a issue to python developers.  This is a python issue.  
For example, meson.exe is also in Scripts folder in python system path:

ls /mnt/c/Users/jmoguillansky/AppData/Local/Programs/Python/Python38/Scripts/

cygdb.exe   cythonize.exe         easy_install.exe  ngl-test-script.py  ngl-viewer-script.py  pip.exe     pip3.exe              pyside2-lupdate.exe  pyside2-uic.exe
cython.exe  easy_install-3.8.exe  meson.exe         ngl-test.exe        ngl-viewer.exe        pip3.8.exe  pyside2-designer.exe  pyside2-rcc.exe      wheel.exe

2021-01-04 18:08 UTC, jmoguillansky-gpsw commented on Makefile
> +	# patch libnodegl.pc TODO: remove
It seems that currently meson pkg-config export doesn't support lib paths with spaces.  
I will post an issue on meson github...

2021-01-04 18:09 UTC, jmoguillansky-gpsw commented on Makefile
> +	(cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)
There's two differences between windows and others:
1) we use cmd.exe
2) we use different slashes (e.g. forward slash instead of backslashes).
It would be great if we can conslidate the code and avoid platform-specific code, but this can be a future improvement.  
It's not so easy to do this in a makefile, easier in a high level programming language like Python, etc.

2021-01-04 18:10 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  message('backend: ' + gbackend_name + ' enabled: ' + all_dep_found.to_string())
ok I'll update...

2021-01-04 18:11 UTC, jmoguillansky-gpsw commented on Makefile
> +MESON_SETUP_NINJA   = meson setup --backend ninja --prefix="$(W_PREFIX)" --pkg-config-path=$(PREFIX)\\Lib\\pkgconfig -Drpath=true
the unit tests target regarding meson setup using ninja.  All the other targets can be built with visual studio backend.

2021-01-04 18:17 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_win.yml
> +          wget https://github.com/jmoguillansky-gpsw/gopro-pkg/blob/master/external/win64/pkg-config.exe?raw=true -O pkg-config.exe
Windows doesn't provide a pkg-config windows executable.  
I extracted it from msys2, and put it for now in a personal repo. 
There doesn't really seem to be a standalone windows pre-built binary available anywhere.  
We can either build this from source as part of node.gl build, or we can provide this in a public ftp server (or something equivalent).

2021-01-05 16:31 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
I get the compile error:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(173,1): fatal error C1189: #error:  "No Target Architecture" [C:\Users\jmoguillansky\Documents\2020\Git\gopro-lib-node.gl-meson-windows-master\builddir\libnodegl\tes
t_utils@exe.vcxproj]

I put in the commit message it fixes compile error "No Target Architecture".  
Is this sufficient detail?

2021-01-05 16:39 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
Can you please help with that change?  
If I recall correctly, glfunctions.h is autogenerated, I don't have to modify it by hand?

2021-01-06 09:12 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +    gbackend_deps += cc.find_library(dep, required: opt_gbackend, dirs: cc_lib_dirs)
I think that workaround is OK, thanks

2021-01-06 09:15 UTC, cboesch-gpsw commented on ngl-tools/meson.build
> +endif
We're just following the recommended practice from here: https://mesonbuild.com/howtox.html#add-math-library-lm-portably

The purpose of `required: false` really is all about this: we want as little platform specific logic and be feature/availability oriented. Please don't change something that works for something more complex.

2021-01-06 16:28 UTC, jmoguillansky-gpsw commented
Updated

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: cboesch-gpsw <notifications@github.com>
Sent: Wednesday, January 6, 2021 1:15:17 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In ngl-tools/meson.build<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r552454256>:

> +if host_system != 'windows'
+  tool_deps += cc.find_library('m', required: false)
+endif


We're just following the recommended practice from here: https://mesonbuild.com/howtox.html#add-math-library-lm-portably

The purpose of required: false really is all about this: we want as little platform specific logic and be feature/availability oriented. Please don't change something that works for something more complex.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r552454256>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEYYHAAX7MVZQJW4EJLSYQS2LANCNFSM4UDAE7OA>.

2021-01-06 20:41 UTC, jmoguillansky-gpsw reviewed
Note that these files were autogenerated on windows platform.  
This is why the line endings are different.

2021-01-07 15:23 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
NGLI_GL_APIENTRY is still needed. The build issue with MSVC is related to the invalid syntax we currently use (which is  accepted by gcc) for declaring the OpenGL function pointers. https://github.com/gopro/gopro-lib-node.gl/pull/166 should addresses the issue.

2021-01-07 16:01 UTC, jbnoel-gpsw commented on .github/workflows/ci_win.yml
> +          wget https://github.com/jmoguillansky-gpsw/gopro-pkg/blob/master/external/win64/pkg-config.exe?raw=true -O pkg-config.exe
I agree with @cboesch-gpsw, we need to limit the hacks.
Ideas:
- prebuilt with github action like other dependencies ?
- https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows ?

2021-01-07 16:07 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  '-o', meson.current_build_dir() / 'gl.xml'
We don't want to do that at every run; please keep the custom target. It doesn't matter if it doesn't work on Windows, just call the script directly if needed.

2021-01-07 16:08 UTC, cboesch-gpsw commented on pynodegl/.gitignore
> +*.dll
Again "update X" is not a good commit message; please squash this into the corresponding commit

2021-01-07 16:10 UTC, cboesch-gpsw commented on Makefile
> +PKG_CONFIG ?= C:\\msys64\\usr\\bin\\pkg-config.exe
Can't we do something about these hardcoded path?

2021-01-07 16:11 UTC, cboesch-gpsw commented on Makefile
> +	($(CMD) xcopy /Y /C builddir\\libnodegl\\*.lib $(PREFIX)\\Lib\\.)
The `( ... )` form is a subshell and is only needed when you use the "activate", you can get rid of them

2021-01-07 16:19 UTC, jmoguillansky-gpsw commented
Regarding hardcoded path, thats the default value.  The user can override (and I override it locally because I use community edition)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: cboesch-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:10:36 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In Makefile<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553426409>:

> +VCVARS64 ?= "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
+ACTIVATE = $(VCVARS64) \&\& $(PREFIX)\\Scripts\\activate.bat
+VCPKG_DIR ?= C:\\vcpkg
+PKG_CONFIG ?= C:\\msys64\\usr\\bin\\pkg-config.exe


Can't we do something about these hardcoded path?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#pullrequestreview-563616092>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUE2SFBBMVH4QYYO3SPLSYXMHZANCNFSM4UDAE7OA>.

2021-01-07 16:22 UTC, jmoguillansky-gpsw commented
Regarding pkg config: yes I'm currently working on a proper solution but its non trivial.  I was able to build "pkgconf" from source: this is supposed to be a drop in replacememt for pkg config but there's compatibility issues on Windows.  It seems I need to patch the source code too... This was meant as a temporary workaround.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: jbnoel-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:01:59 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@jbnoel-gpsw commented on this pull request.

________________________________

In .github/workflows/ci_win.yml<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553420998>:

> +      run:
+        shell: wsl-bash {0}
+
+    steps:
+      - uses: Vampire/setup-wsl@v1
+        with:
+          distribution: Ubuntu-20.04
+
+      - uses: actions/checkout@v2
+
+      - name: Install dependencies
+        run: |
+          sudo apt -y update
+          sudo apt -y install build-essential zip
+          pip.exe install meson
+          wget https://github.com/jmoguillansky-gpsw/gopro-pkg/blob/master/external/win64/pkg-config.exe?raw=true -O pkg-config.exe


I agree with @cboesch-gpsw<https://github.com/cboesch-gpsw>, we need to limit the hacks.
Ideas:

  *   prebuilt with github action like other dependencies ?
  *   https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553420998>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUE22PBWZK3ACKERFASLSYXLHPANCNFSM4UDAE7OA>.

2021-01-07 16:36 UTC, jmoguillansky-gpsw commented
What about using run_command on msvc and custom target on others?

From: cboesch-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:08 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In libnodegl/meson.build<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553424689>:

> +run_command('curl',

+  'https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml',

+  '-o', meson.current_build_dir() / 'gl.xml'

We don't want to do that at every run; please keep the custom target. It doesn't matter if it doesn't work on Windows, just call the script directly if needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#pullrequestreview-563613665>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUE6T2XYBTS3OIKQTPDTSYXL5FANCNFSM4UDAE7OA>.

2021-01-07 16:38 UTC, cboesch-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
Yes but why re-ordering fix it? What includes set the architecture, and what is complaining about this missing architecture?

2021-01-07 16:40 UTC, cboesch-gpsw commented on .gitattributes
> +* -text
Also, doesn't this affect all binaries? Like, is git going to consider our images in the doc as text now?

2021-01-07 16:40 UTC, jmoguillansky-gpsw commented
Winnt.h which indirectly included by some other include…
Not so easy to trace the culprit

From: cboesch-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:39 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In libnodegl/utils.c<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553443678>:

> +#define POW10_9 1000000000

+#include <Windows.h>

Yes but why re-ordering fix it? What includes set the architecture, and what is complaining about this missing architecture?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553443678>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUE55QDPGOOWOOZWX5HTSYXPR5ANCNFSM4UDAE7OA>.

2021-01-07 16:44 UTC, jmoguillansky-gpsw commented
gitattributes(5) (kernel.org)<https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitattributes.html>

text
This attribute enables and controls end-of-line normalization. When a text file is normalized, its line endings are converted to LF in the repository. To control what line ending style is used in the working directory, use the eol attribute for a single file and the core.eol configuration variable for all text files. Note that setting core.autocrlf to true or input overrides core.eol (see the definitions of those options in git-config(1)<https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-config.html>).

We’re disabling this feature (the minus in front) so we’re disabling end-of-line normalization. It won’t affect any binaries, etc.  All this does is turn off end-of-line normalization of text files.


From: cboesch-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:40 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In .gitattributes<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553444555>:

> @@ -0,0 +1 @@

+* -text

Also, doesn't this affect all binaries? Like, is git going to consider our images in the doc as text now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553444555>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEYEXTIMJKCJHRZECALSYXPXLANCNFSM4UDAE7OA>.

2021-01-07 16:51 UTC, cboesch-gpsw commented on Makefile
> +	@echo "        . $(PREFIX)\\Scripts\\activate.bat"
this file doesn't exist

2021-01-07 16:52 UTC, cboesch-gpsw commented on Makefile
> +ACTIVATE = $(PREFIX)/bin/activate
why not integrate `cmd.exe` into `ACTIVATE` to help the different if branches?

2021-01-07 16:52 UTC, cboesch-gpsw commented on Makefile
> +	($(CMD) $(ACTIVATE) \&\& $(MESON_SETUP) ngl-tools builddir\\ngl-tools \&\& $(MESON_COMPILE) -C builddir\\ngl-tools \&\& $(MESON_INSTALL) -C builddir\\ngl-tools)
why do you need to escape the `&`?

2021-01-07 17:28 UTC, jmoguillansky-gpsw commented
It exists on windows

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: cboesch-gpsw <notifications@github.com>
Sent: Thursday, January 7, 2021 8:53:05 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@cboesch-gpsw commented on this pull request.

________________________________

In Makefile<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553452156>:

>       @echo

 ngl-tools-install: nodegl-install
+ifeq ($(TARGET_OS),Windows)
+       ($(CMD) $(ACTIVATE) \&\& $(MESON_SETUP) ngl-tools builddir\\ngl-tools \&\& $(MESON_COMPILE) -C builddir\\ngl-tools \&\& $(MESON_INSTALL) -C builddir\\ngl-tools)


why do you need to escape the &?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#pullrequestreview-563651325>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEY5L7FYSYALWZADRJTSYXRHDANCNFSM4UDAE7OA>.

2021-01-07 17:30 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/glincludes.h
>  #define NGLI_GL_APIENTRY
I tried #166 but still get compile errors (see jmoguillansky/meson-windows-master-tmp-gl-apientry)...

2021-01-07 17:30 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  '-o', meson.current_build_dir() / 'gl.xml'
how about if we use "run_command" on msvc and "custom_target" for others, and put a comment that this is a temporary solution?

2021-01-07 17:31 UTC, jmoguillansky-gpsw commented on Makefile
> +PKG_CONFIG ?= C:\\msys64\\usr\\bin\\pkg-config.exe
those are the default params, the user can override

2021-01-07 17:33 UTC, jmoguillansky-gpsw commented on Makefile
> +	@echo "        . $(PREFIX)\\Scripts\\activate.bat"
It exists on windows (with msvc)

2021-01-07 17:34 UTC, jmoguillansky-gpsw commented on Makefile
> +ACTIVATE = $(PREFIX)/bin/activate
cmd is running more commands than just activate.  It's doing activate and meson setup and meson compile, etc.  Putting cmd inside activate is a bit misleading

2021-01-07 17:35 UTC, jmoguillansky-gpsw commented on Makefile
> +	($(CMD) $(ACTIVATE) \&\& $(MESON_SETUP) ngl-tools builddir\\ngl-tools \&\& $(MESON_COMPILE) -C builddir\\ngl-tools \&\& $(MESON_INSTALL) -C builddir\\ngl-tools)
good question.  This is one of the tricky integration issues.  I'm passing ampersand to be processed by cmd executable instead of by bash shell (hence using the escape character).  I had to deal with various issues regarding slashes and ampersands etc.

2021-01-07 18:25 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_win.yml
> +          wget https://github.com/jmoguillansky-gpsw/gopro-pkg/blob/master/external/win64/pkg-config.exe?raw=true -O pkg-config.exe
Regarding pkg config: yes I'm currently working on a proper solution but its non trivial.  I was able to build "pkgconf" from source: this is supposed to be a drop in replacememt for pkg config but there's compatibility issues on Windows.  It seems I need to patch the source code too... This was meant as a temporary workaround.

FYI:
when I build with "pkg-config" from msys2:

Called `C:\Users\jmoguillansky\Documents\2020\Git\gopro-lib-node.gl-meson-windows-master\nodegl-env\Scripts\pkg-config.EXE sdl2 --libs` -> 0
-L -L/manual-link -lSDL2 -lSDL2main -ldinput8 -lshell32 -lsetupapi -ladvapi32 -luuid -lversion -loleaut32 -lole32 -limm32 -lwinmm -lgdi32 -luser32 -lSDL2

When I build with "pkgconf" (built from source):
Called `C:\Users\jmoguillansky\Documents\2020\Git\gopro-lib-node.gl-meson-windows-master\nodegl-env\Scripts\pkg-config.EXE sdl2 --libs` -> 0
-L -lSDL2 -L/manual-link -lSDL2main

I need to add param "--static".  There's various other incompatibilities like backslashes instead of forward slashes, etc

2021-01-08 01:53 UTC, jmoguillansky-gpsw commented on .gitattributes
> +* -text
gitattributes(5) (kernel.org)<https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitattributes.html>

text
This attribute enables and controls end-of-line normalization. When a text file is normalized, its line endings are converted to LF in the repository. To control what line ending style is used in the working directory, use the eol attribute for a single file and the core.eol configuration variable for all text files. Note that setting core.autocrlf to true or input overrides core.eol (see the definitions of those options in git-config(1)<https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-config.html>).

We’re disabling this feature (the minus in front) so we’re disabling end-of-line normalization. It won’t affect any binaries, etc.  All this does is turn off end-of-line normalization of text files.

2021-01-08 08:22 UTC, ubitux commented on .gitattributes
> +* -text
So it means someone working on windows may start submitting files with CLRF line endings?

Unless I'm mistaken, this is only needed for writing file, so it's not about the clone itself. Why do you need to write files in the first place? Is that related to the OpenGL wrapper thing?

2021-01-08 08:23 UTC, ubitux commented on Makefile
> +	@echo "        . $(PREFIX)\\Scripts\\activate.bat"
My bad I misunderstood.

2021-01-08 08:27 UTC, ubitux commented on Makefile
> +ACTIVATE = $(PREFIX)/bin/activate
`CMD = .` then?

2021-01-08 08:37 UTC, ubitux commented on Makefile
> +	(cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)
> we use different slashes (e.g. forward slash instead of backslashes).

I though windows was supporting `/` nowadays?

> It's not so easy to do this in a makefile, easier in a high level programming language like Python, etc.

I'm not opposed to having Windows handled outside the Makefile (we moved away from make for the build for a reason). I don't know if Python would be a great language for bootstrapping packages etc on Windows (because it requires an initial installation for the user and we will need to create a virtual env from another Python script, it might get clumsy), but I wouldn't be particularly opposed to that. Isn't Powershell moer appropriate? (I really don't know).

If you were under the impression that I was asking for Windows integration within the Makefile, I'm sorry. The goal of that Makefile is to bootstrap the environment: we kept make because on Unix it's extremely convenient. The keyword here is "convenient", so the question to answer on windows is: "what would be the most convenient way for a user to bootstrap the environment reliably?".

2021-01-08 15:24 UTC, jmoguillansky-gpsw commented
No what it means is that if you submit a text file with /n on windows, git will convert to /r/n.  We don't want git changing the line endings we can manage them ourselves

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Clément Bœsch <notifications@github.com>
Sent: Friday, January 8, 2021 12:37:38 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@ubitux commented on this pull request.

________________________________

In Makefile<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>:

> @@ -225,13 +225,25 @@ else
 endif

 tests: nodegl-tests tests-setup
+ifeq ($(TARGET_OS),Windows)
+       (cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)


we use different slashes (e.g. forward slash instead of backslashes).

I though windows was supporting / nowadays?

It's not so easy to do this in a makefile, easier in a high level programming language like Python, etc.

I'm not opposed to having Windows handled outside the Makefile (we moved away from make for the build for a reason). I don't know if Python would be a great language for bootstrapping packages etc on Windows (because it requires an initial installation for the user and we will need to create a virtual env from another Python script, it might get clumsy), but I wouldn't be particularly opposed to that. Isn't Powershell moer appropriate? (I really don't know).

If you were under the impression that I was asking for Windows integration within the Makefile, I'm sorry. The goal of that Makefile is to bootstrap the environment: we kept make because on Unix it's extremely convenient. The keyword here is "convenient", so the question to answer on windows is: "what would be the most convenient way for a user to bootstrap the environment reliably?".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEZPPJEKY5LD3I2GL3LSY275FANCNFSM4UDAE7OA>.

2021-01-08 15:27 UTC, jmoguillansky-gpsw commented
Regarding supporting backslashes: not command prompt and I'm not familiar with powershell.  I used bash and Makefile because its the minimal porting effort.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Clément Bœsch <notifications@github.com>
Sent: Friday, January 8, 2021 12:37:38 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@ubitux commented on this pull request.

________________________________

In Makefile<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>:

> @@ -225,13 +225,25 @@ else
 endif

 tests: nodegl-tests tests-setup
+ifeq ($(TARGET_OS),Windows)
+       (cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)


we use different slashes (e.g. forward slash instead of backslashes).

I though windows was supporting / nowadays?

It's not so easy to do this in a makefile, easier in a high level programming language like Python, etc.

I'm not opposed to having Windows handled outside the Makefile (we moved away from make for the build for a reason). I don't know if Python would be a great language for bootstrapping packages etc on Windows (because it requires an initial installation for the user and we will need to create a virtual env from another Python script, it might get clumsy), but I wouldn't be particularly opposed to that. Isn't Powershell moer appropriate? (I really don't know).

If you were under the impression that I was asking for Windows integration within the Makefile, I'm sorry. The goal of that Makefile is to bootstrap the environment: we kept make because on Unix it's extremely convenient. The keyword here is "convenient", so the question to answer on windows is: "what would be the most convenient way for a user to bootstrap the environment reliably?".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEZPPJEKY5LD3I2GL3LSY275FANCNFSM4UDAE7OA>.

2021-01-08 15:30 UTC, jmoguillansky-gpsw commented
I don't think we should have makefile for one platform and something else for other platforms, ideally we use the same thing for both.  I'm ok with Makefile.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Jeffrey Moguillansky <jmoguillansky@gopro.com>
Sent: Friday, January 8, 2021 7:27:18 AM
To: gopro/gopro-lib-node.gl <reply@reply.github.com>; gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)

Regarding supporting backslashes: not command prompt and I'm not familiar with powershell.  I used bash and Makefile because its the minimal porting effort.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Clément Bœsch <notifications@github.com>
Sent: Friday, January 8, 2021 12:37:38 AM
To: gopro/gopro-lib-node.gl <gopro-lib-node.gl@noreply.github.com>
Cc: Jeffrey Moguillansky <jmoguillansky@gopro.com>; Author <author@noreply.github.com>
Subject: Re: [gopro/gopro-lib-node.gl] Port to Windows / Visual Studio Toolchain on Master Branch (#152)


@ubitux commented on this pull request.

________________________________

In Makefile<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>:

> @@ -225,13 +225,25 @@ else
 endif

 tests: nodegl-tests tests-setup
+ifeq ($(TARGET_OS),Windows)
+       (cmd.exe /C $(ACTIVATE) \&\& meson test $(MESON_TESTS_SUITE_OPTS) -C builddir\\tests)


we use different slashes (e.g. forward slash instead of backslashes).

I though windows was supporting / nowadays?

It's not so easy to do this in a makefile, easier in a high level programming language like Python, etc.

I'm not opposed to having Windows handled outside the Makefile (we moved away from make for the build for a reason). I don't know if Python would be a great language for bootstrapping packages etc on Windows (because it requires an initial installation for the user and we will need to create a virtual env from another Python script, it might get clumsy), but I wouldn't be particularly opposed to that. Isn't Powershell moer appropriate? (I really don't know).

If you were under the impression that I was asking for Windows integration within the Makefile, I'm sorry. The goal of that Makefile is to bootstrap the environment: we kept make because on Unix it's extremely convenient. The keyword here is "convenient", so the question to answer on windows is: "what would be the most convenient way for a user to bootstrap the environment reliably?".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/gopro/gopro-lib-node.gl/pull/152#discussion_r553808615>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3BUEZPPJEKY5LD3I2GL3LSY275FANCNFSM4UDAE7OA>.

2021-01-08 17:53 UTC, jmoguillansky-gpsw commented on Makefile
> +ACTIVATE = $(PREFIX)/bin/activate
sure I'll update

2021-01-08 18:30 UTC, jmoguillansky-gpsw commented on Makefile
> +ACTIVATE = $(PREFIX)/bin/activate
let me know if this is better: https://github.com/gopro/gopro-lib-node.gl/pull/152/commits/7ca08730e1720b34116ee94f0e5418e9a91fc3fc

2021-01-08 23:19 UTC, jmoguillansky-gpsw commented
some recent updates:
1) added params --includedir and --libdir when calling meson setup to point to $(PREFIX)\Include and $(PREFIX)\Lib.  
This also fixes the pkg-config generation issue: now the generated pkg-config files point to correct location.
2) updated pkg-config patch:
set params "--keep-system-cflags and --keep-system-libs" automatically.  This resolves an issue where various pkg-config cflags and libs params were being filtered out by pkg-config (pkg-config thinks these directories are system paths but they're not).

2021-02-05 18:21 UTC, cboesch-gpsw commented
Merged with https://github.com/gopro/gopro-lib-node.gl/pull/177

2021-02-05 18:21 UTC, closed without merging