Port misc code to windows
gopro/gopro-lib-node.gl pull request #153
Opened 2020-12-01 18:42 UTC by jmoguillansky-gpsw

2020-12-02 17:24 UTC, cboesch-gpsw requested changes

2020-12-02 17:24 UTC, cboesch-gpsw commented on libnodegl/log.c
> +#ifndef _WIN32
please keep this check coherent with the check at line 45: `#if !defined(TARGET_IPHONE) && !defined(TARGET_ANDROID) && !defined(TARGET_MINGW_W64)`

But ideally, I'd suggest to make a dedicated commit in which you add `conf_data.set10('HAVE_ISATTY', cc.has_function('isatty'))` to the `meson.build` and protect the include+code with `#if HAVE_ISATTY`

2020-12-02 17:24 UTC, cboesch-gpsw commented on libnodegl/node_camera.c
> -#include <unistd.h>
Can we have a dedicated commit for this: "camera: remove unused unistd.h include"?

That way, with the `isatty` change isolated as well, you can reword the current commit to something more explicit: "internal: replace read/write with fread/fwrite", and in the description: "This removes the unix specific unistd.h include, not supported with MSVC."

2020-12-02 17:24 UTC, cboesch-gpsw commented on libnodegl/utils.c
> -int64_t ngli_gettime(void)
please add the "unused" qualifier in the commit message.

2020-12-02 17:24 UTC, cboesch-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
We are using the non-capitalized form in `libnodegl/backends/gl/glcontext_wgl.c`: which one is correct?

2020-12-02 17:24 UTC, cboesch-gpsw commented on libnodegl/utils.c
> +    GetSystemTimeAsFileTime(&t0);
This is not appropriate for a monotonic clock: you probably need to use `QueryPerformance{Frequency,Counter}`. `GetSystemTimeAsFileTime` would only be appropriate for the real time.

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/common.c
> +    return gettime_relative();
This will become invalid when you will fix `gettime_relative()` to be properly monotonic.

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/common.c
> +    return 1000000 * (int64_t)ts.tv_sec + ts.tv_nsec / 1000;
What is this change for?

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/ngl-serialize.c
> +#define STDERR_FILENO _fileno(stderr)
I believe you want those only in `_MSC_VER`

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/opts.c
> -#include <sys/time.h>
A dedicated commit for this unused include please

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/ngl-serialize.c
> +#include <unistd.h>
All system includes need to be after the definition of `_POSIX_C_SOURCE`

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/ngl-ipc.c
> +#define ssize_t int
I'm uncomfortable setting `ssize_t` for `_WIN32` (it's defined on mingw), I'd rather have it for MSVC only. That said, in this file, I think you can make `recv(s->upload_fd, s->upload_buffer, UPLOAD_CHUNK_SIZE, 0)` return an int: `UPLOAD_CHUNK_SIZE` will never require more than what an int can store, so it's fine to downcast on platforms that have a `ssize_t` returned.

2020-12-02 17:24 UTC, cboesch-gpsw commented on ngl-tools/ipc.c
> +#define ssize_t int
Similar to my other comment in `ngl-ipc`, I think it's best if we use an `int` here as well. Please make a dedicated commit for that one and the change in `ngl-ipc`: a commit specially about `ssize_t`

2020-12-02 17:30 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
Windows.h (with uppercase)

2020-12-02 17:40 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +    return 1000000 * (int64_t)ts.tv_sec + ts.tv_nsec / 1000;
I'll remove it.  Probably got there by accident

2020-12-02 17:41 UTC, cboesch-gpsw commented on libnodegl/utils.c
> +#include <Windows.h>
Alright: would you mind adding a commit to fix the one in `glcontext_wgl.c`?

2020-12-02 22:26 UTC, jmoguillansky-gpsw commented on libnodegl/log.c
> +#ifndef _WIN32
I can add the following logic: 
in meson.build:
define TARGET_WINDOWS + TARGET_MINGW_W64 on windows / mingw,
define TARGET_WINDOWS + TARGET_MSVC on windows /  msvc
use: #if !defined(TARGET_IPHONE) && !defined(TARGET_ANDROID) && !defined(TARGET_WINDOWS)

2020-12-04 14:42 UTC, mbouron-gpsw commented on libnodegl/meson.build
> +  if cc.get_id() != 'msvc'
Maybe use this form:
`if cc.get_id() == 'msvc'
  conf_data.set10('TARGET_MSVC', true)
else
  conf_data.set10('TARGET_MINGW_W64', true)
endif`

2020-12-04 14:48 UTC, mbouron-gpsw commented on libnodegl/log.c
> +#endif
This should be part of a separate commit (it is not tied to the usage of open/read/write)).

2020-12-04 14:48 UTC, mbouron-gpsw commented on libnodegl/log.c
> +#if !defined(TARGET_IPHONE) && !defined(TARGET_ANDROID) && !defined(TARGET_WINDOWS)
Same as above.

2020-12-04 14:52 UTC, mbouron-gpsw commented on libnodegl/node_buffer.c
> +    fseek(s->fp, 0, SEEK_END);
Shouldn't the return of fseek be checked ?

2020-12-04 14:55 UTC, mbouron-gpsw commented on libnodegl/node_buffer.c
>      if (n < 0) {
The error condition should be adjusted as well, fread cannot return a negative number. Quoting the documenation:
`fread() does not distinguish between end-of-file and error, and callers must use feof(3) and ferror(3) to determine which occurred.`

2020-12-04 14:57 UTC, mbouron-gpsw commented on libnodegl/utils.c
> +//reference: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
Please align the comment with the code bellow.

2020-12-04 14:57 UTC, mbouron-gpsw commented on libnodegl/utils.c
> +    int64_t tv_nsec = (int) (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);
extra space between (int) and (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);

2020-12-04 14:58 UTC, mbouron-gpsw commented on libnodegl/utils.c
> +    return ret != 0 ? 0 : ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
This should be part of another commit that checks the return of clock_gettime().

2020-12-04 14:59 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +//reference: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
Please align the comment with the code below.

2020-12-04 14:59 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +    int64_t tv_nsec = (int) (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);
Extra space between (int) and (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);

2020-12-04 14:59 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +        const int n = fread(buf + pos, 1, BUF_SIZE, fp);
int -> size_t

2020-12-04 15:00 UTC, mbouron-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
The error condition should be adjusted (n cannot be negative with fread()).

2020-12-04 15:01 UTC, mbouron-gpsw commented on ngl-tools/ipc.c
> +        const int n = recv(fd, buf + nr, size - nr, 0);
n should still be a ssize_t.

2020-12-04 15:08 UTC, mbouron-gpsw commented on libnodegl/utils.c
> +//reference: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
Alse please add a space between // and the comment

2020-12-04 15:11 UTC, mbouron-gpsw commented on libnodegl/node_buffer.c
> +    fseek(s->fp, 0, SEEK_END);
Does this handle files >= 4gb ?

2020-12-04 15:27 UTC, jmoguillansky-gpsw commented on libnodegl/node_buffer.c
> +    fseek(s->fp, 0, SEEK_END);
we use ftell to get the filesize right after

2020-12-04 15:28 UTC, ubitux commented on libnodegl/log.c
> +#ifndef _WIN32
or you can just use `defined(_WIN32)` for both

2020-12-04 15:29 UTC, jmoguillansky-gpsw commented on libnodegl/node_buffer.c
> +    fseek(s->fp, 0, SEEK_END);
the "data_size" variable is a 32 bit int, so I'm not sure this current code would handle 4 gb files.  Not sure we have to worry about this issue at this point?

2020-12-04 15:32 UTC, jmoguillansky-gpsw commented on libnodegl/node_buffer.c
>      if (n < 0) {
updated

2020-12-04 15:34 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +//reference: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
updated

2020-12-04 15:36 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +    return ret != 0 ? 0 : ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
The main motivation was to have the same code as ngl-tools/common.c but you're right checking the return value could be helpful

2020-12-04 15:38 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +    int64_t tv_nsec = (int) (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);
updated

2020-12-04 15:38 UTC, jmoguillansky-gpsw commented on libnodegl/log.c
> +#endif
Ok, but let's resolve the higher-priority issues first

2020-12-04 15:40 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +//reference: https://github.com/mirror/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
Updated

2020-12-04 15:42 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +    int64_t tv_nsec = (int) (((pc.QuadPart % pf.QuadPart) * POW10_9 + (pf.QuadPart >> 1)) / pf.QuadPart);
updated

2020-12-04 15:44 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +        const int n = fread(buf + pos, 1, BUF_SIZE, fp);
updated

2020-12-04 15:48 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
I think this code can be simplified significantly:
Seek to the end of the file, get the file size, and then read the entire contents with one call to fread?

2020-12-04 15:50 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
nm I see, you may be reading from stdin when filename is empty string

2020-12-04 15:52 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
When you read from stdin, how do you know that end of data is reached?  This code assumes that the only input to stdin is the buffer data and nothing else?

2020-12-04 15:53 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
Might be better if you pass the data size and then the data

2020-12-04 15:56 UTC, ubitux commented on ngl-tools/common.c
>          if (n < 0) {
> When you read from stdin, how do you know that end of data is reached? This code assumes that the only input to stdin is the buffer data and nothing else?

`read()` returns `0` at `EOF`:
```c
        if (n == 0) {
            buf[pos] = 0;
            break;
        }
```

2020-12-04 17:44 UTC, mbouron-gpsw commented on libnodegl/node_buffer.c
> +    fseek(s->fp, 0, SEEK_END);
We don't have to worry about supporting files >= 4gb for now, I was just curious about how it is handled with these functions. I think we should check the return of fseek() so we indicate that an error happened at the file level, otherwise we will reach the error block below:
``` c
    if (s->data_size != s->count * s->data_stride) {
        LOG(ERROR,
            "element count (%d) and data stride (%d) does not match data size (%d)",
            s->count,
            s->data_stride,
            s->data_size);
        return NGL_ERROR_INVALID_DATA;
    }
```

which is not too indicative about the original error.

2020-12-04 17:47 UTC, mbouron-gpsw commented on libnodegl/utils.c
> +    return ret != 0 ? 0 : ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
Makes sense, just split theses changes in a separate commit and it is fine.

2020-12-04 17:59 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
>          if (n < 0) {
yes I know I understand how the code works.  I meant is this the right logic?  With this logic we can't pass additional data after the buffer in stdin.

2020-12-04 18:09 UTC, jmoguillansky-gpsw commented on libnodegl/log.c
> +#ifndef _WIN32
TARGET_WINDOWS is basically synonymous with _WIN32.  I can remove TARGET_WINDOWS?

2020-12-04 18:32 UTC, jmoguillansky-gpsw commented on libnodegl/log.c
> +#if !defined(TARGET_IPHONE) && !defined(TARGET_ANDROID) && !defined(TARGET_WINDOWS)
should this be TARGET_MSVC?  Windows / msvc doesn't support unistd.h, and also related to open/write/write

2020-12-04 18:34 UTC, mbouron-gpsw commented on libnodegl/log.c
> +#endif
Isn't this one about isatty() ?

2020-12-04 18:42 UTC, jmoguillansky-gpsw commented on libnodegl/utils.c
> +    return ret != 0 ? 0 : ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
updated

2020-12-04 19:24 UTC, mbouron-gpsw commented on libnodegl/node_buffer.c
>          LOG(ERROR, "could not read '%s': %zd", s->filename, n);
The error message should be changed to LOG(ERROR, "could not read '%s'", s->filename);

2020-12-04 19:37 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +        if (feof(fp)) {
You want to increment pos before checking for EOF otherwise buf will be incomplete.

2020-12-04 19:40 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +        if (feof(fp)) {
there's already pos += n later.  If we hit EOF we goto end, and pos isn't used there?

2020-12-04 19:48 UTC, jmoguillansky-gpsw commented on libnodegl/log.c
> +#endif
Sorry you're right.  updated

2020-12-04 19:59 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +        if (feof(fp)) {
If you check for EOF before executing pos +=n, the null character will be inserted in the wrong place truncating the buffer.

2020-12-04 20:02 UTC, mbouron-gpsw commented on ngl-tools/common.c
> +        if (ferror(n)) {
ferror(n) -> ferror(fp)

2020-12-04 20:04 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +        if (feof(fp)) {
sorry you're right.  updated

2020-12-04 20:06 UTC, jmoguillansky-gpsw commented on ngl-tools/common.c
> +        if (ferror(n)) {
thanks, updated

2020-12-08 13:34 UTC, mbouron-gpsw commented on ngl-tools/ngl-ipc.c
> +        s->upload_fd = open(filename, O_RDONLY);
This should be ported to fopen().

2020-12-08 13:34 UTC, mbouron-gpsw commented on ngl-tools/ngl-ipc.c
> +        const int n = recv(s->upload_fd, s->upload_buffer, UPLOAD_CHUNK_SIZE, 0);
fread().

2020-12-08 13:46 UTC, mbouron-gpsw commented on ngl-tools/ngl-ipc.c
> +        s->upload_fd = open(filename, O_RDONLY);
The ngl-desktop.c counterpart should also be ported to fopen()/fwrite().

2020-12-08 22:08 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-ipc.c
> +        s->upload_fd = open(filename, O_RDONLY);
strange that there's no compiler errors on windows

2020-12-08 23:14 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-ipc.c
> +        s->upload_fd = open(filename, O_RDONLY);
updated

2020-12-08 23:15 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-ipc.c
> +        const int n = recv(s->upload_fd, s->upload_buffer, UPLOAD_CHUNK_SIZE, 0);
updated

2020-12-10 10:00 UTC, mbouron-gpsw commented
Merged in https://github.com/gopro/gopro-lib-node.gl/pull/153.

2020-12-10 10:00 UTC, closed without merging