nodegl: rename class to clazz
gopro/gopro-lib-node.gl pull request #194
Opened 2021-02-19 16:18 UTC by jmoguillansky-gpsw

We should avoid using C++ keywords, especially in headers, so that
node.gl code can be used from both C and C++

2021-02-19 17:00 UTC, cboesch-gpsw commented
We're already using `cls`; can we make that consistent?

2021-02-19 17:08 UTC, mbouron-gpsw commented
@cboesch-gpsw  clazz is also used in some of our jni code.

2021-02-19 17:12 UTC, cboesch-gpsw commented
> @cboesch-gpsw clazz is also used in some of our jni code.

Alright well then, let's decide on renaming either `cls` or `clazz` for consistency first.

2021-02-19 17:19 UTC, mbouron-gpsw commented
I'm ok with `cls` if it's ok with everyone (and I'll make a commit to rename the jni part).

2021-02-19 18:01 UTC, jmoguillansky-gpsw commented
sure I can change to cls

2021-02-19 21:58 UTC, cboesch-gpsw commented on libnodegl/gctx.c
> +extern const struct gctx_cls ngli_gctx_gles;
I don't think you want to rename that struct

2021-02-19 21:58 UTC, cboesch-gpsw commented on libnodegl/gctx.c
> +    const struct gctx_class *cls = backend_map[config->backend].cls;
especially since you're not renaming it here ^

2021-02-19 22:00 UTC, cboesch-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_draw(s, nb_vertices, nb_instances);
that added return looks unrelated and wrong

2021-02-19 22:00 UTC, cboesch-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_draw_indexed(s, indices, indices_format, nb_indices, nb_instances);
idem added return

2021-02-19 22:00 UTC, cboesch-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_dispatch(s, nb_group_x, nb_group_y, nb_group_z);
idem added return

2021-02-19 23:10 UTC, jmoguillansky-gpsw commented on libnodegl/gctx.c
> +extern const struct gctx_cls ngli_gctx_gles;
updated

2021-02-19 23:10 UTC, jmoguillansky-gpsw commented on libnodegl/gctx.c
> +    const struct gctx_class *cls = backend_map[config->backend].cls;
updated

2021-02-19 23:11 UTC, jmoguillansky-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_draw(s, nb_vertices, nb_instances);
updated

2021-02-19 23:11 UTC, jmoguillansky-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_draw_indexed(s, indices, indices_format, nb_indices, nb_instances);
updated

2021-02-19 23:11 UTC, jmoguillansky-gpsw commented on libnodegl/pipeline.c
> +    return s->gctx->cls->pipeline_dispatch(s, nb_group_x, nb_group_y, nb_group_z);
updated

2021-02-20 09:31 UTC, mbouron-gpsw approved these changes

2021-02-20 09:45 UTC, cboesch-gpsw commented
Extract of `git grep '\<class\>'` in your branch:
```
libnodegl/gen_doc.c:#define CLASS_LIST(type_name, class) extern const struct node_class class;
libnodegl/gen_doc.c:#define TYPE2CLASS(type_name, class)            \
libnodegl/gen_doc.c:        extern const struct node_class class;   \
libnodegl/gen_doc.c:        return &class;                          \
libnodegl/gen_doc.c:static void print_node_type(struct bstr *b, const struct node_class *class)
libnodegl/gen_doc.c:    const char *class_ref = class->params_id ? class->params_id : class->name;
libnodegl/gen_doc.c:    ngli_bstr_printf(b, "[%s](#", class->name);
libnodegl/gen_doc.c:#define CLASS_COMMALIST(type_name, class) &class,
libnodegl/gen_specs.c:#define CLASS_LIST(type_name, class) extern const struct node_class class;
libnodegl/gen_specs.c:#define CLASS_COMMALIST(type_name, class) &class,
libnodegl/jni_utils.c:        LOG(ERROR, "could not find Throwable class");
libnodegl/jni_utils.c:        LOG(ERROR, "could not find Throwable class's class");
libnodegl/jni_utils.h: * Jni field describing a class, a field or a method to be retrieved using
libnodegl/jni_utils.h: * Retrieve class references, field ids and method ids to an arbitrary structure.
libnodegl/jni_utils.h: * the class/field/method to be retrieved
libnodegl/jni_utils.h: * Delete class references, field ids and method ids of an arbitrary structure.
libnodegl/jni_utils.h: * the class/field/method to be deleted
libnodegl/nodes.c:static struct ngl_node *node_create(const struct node_class *class)
libnodegl/nodes.c:    node = aligned_allocz(node_size + class->priv_size);
libnodegl/nodes.c:    node->cls = class;
libnodegl/nodes.c:#define REGISTER_NODE(type_name, class)         \
libnodegl/nodes.c:        extern const struct node_class class;   \
libnodegl/nodes.c:        ngli_assert(class.id == type_name);     \
libnodegl/nodes.c:        return &class;                          \
libnodegl/nodes.c:    const struct node_class *class = get_node_class(type);
libnodegl/nodes.c:    if (!class) {
libnodegl/nodes.c:    struct ngl_node *node = node_create(class);
```

2021-02-20 09:47 UTC, mbouron-gpsw requested changes
The name class is still used  is nodes.c gen_specs.c, gen_doc.c.

2021-02-21 11:12 UTC, mbouron-gpsw commented
Also please reword the commit message to `internal: rename class to cls` and add a period at the end of the description.

2021-02-22 18:31 UTC, jmoguillansky-gpsw commented
> Extract of `git grep '\<class\>'` in your branch:
> 
> ```
> libnodegl/gen_doc.c:#define CLASS_LIST(type_name, class) extern const struct node_class class;
> libnodegl/gen_doc.c:#define TYPE2CLASS(type_name, class)            \
> libnodegl/gen_doc.c:        extern const struct node_class class;   \
> libnodegl/gen_doc.c:        return &class;                          \
> libnodegl/gen_doc.c:static void print_node_type(struct bstr *b, const struct node_class *class)
> libnodegl/gen_doc.c:    const char *class_ref = class->params_id ? class->params_id : class->name;
> libnodegl/gen_doc.c:    ngli_bstr_printf(b, "[%s](#", class->name);
> libnodegl/gen_doc.c:#define CLASS_COMMALIST(type_name, class) &class,
> libnodegl/gen_specs.c:#define CLASS_LIST(type_name, class) extern const struct node_class class;
> libnodegl/gen_specs.c:#define CLASS_COMMALIST(type_name, class) &class,
> libnodegl/nodes.c:static struct ngl_node *node_create(const struct node_class *class)
> libnodegl/nodes.c:    node = aligned_allocz(node_size + class->priv_size);
> libnodegl/nodes.c:    node->cls = class;
> libnodegl/nodes.c:#define REGISTER_NODE(type_name, class)         \
> libnodegl/nodes.c:        extern const struct node_class class;   \
> libnodegl/nodes.c:        ngli_assert(class.id == type_name);     \
> libnodegl/nodes.c:        return &class;                          \
> libnodegl/nodes.c:    const struct node_class *class = get_node_class(type);
> libnodegl/nodes.c:    if (!class) {
> libnodegl/nodes.c:    struct ngl_node *node = node_create(class);
> ```

updated

2021-02-22 18:35 UTC, jmoguillansky-gpsw commented
> Also please reword the commit message to `internal: rename class to cls` and add a period at the end of the description.

updated

2021-02-22 18:35 UTC, jmoguillansky-gpsw commented
> The name class is still used is nodes.c gen_specs.c, gen_doc.c.

updated

2021-02-22 20:36 UTC, mbouron-gpsw commented
LGTM, thanks.

2021-02-23 09:18 UTC, mbouron-gpsw approved these changes

2021-02-23 09:19 UTC, merged