add GPU capture via renderdoc
gopro/gopro-lib-node.gl pull request #196
Opened 2021-02-19 17:18 UTC by jmoguillansky-gpsw

2021-02-19 22:10 UTC, cboesch-gpsw commented on libnodegl/tools/capture/capture.h
> +#endif
please follow the coding style of the project

2021-02-19 22:15 UTC, cboesch-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +    assert(ret == 1);
please add proper error management, it doesn't matter that this is a development only feature.

2021-02-19 22:15 UTC, cboesch-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +    if (!mod) fprintf(stderr, "could not load librenderdoc.so: %s", dlerror());
i believe we already reviewed that in the past: `LOG()`

2021-02-19 22:16 UTC, cboesch-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +void init_capture(void) {
style

2021-02-19 22:16 UTC, cboesch-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +void* _capture_device = NULL; //TODO: remove
you fixed that already...

2021-02-24 22:59 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/capture.h
> +#endif
updated

2021-02-24 22:59 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +    if (!mod) fprintf(stderr, "could not load librenderdoc.so: %s", dlerror());
sorry about that.  
Updated, now it's basically where we left off last time

2021-02-24 23:00 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +void init_capture(void) {
updated

2021-02-24 23:00 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +void* _capture_device = NULL; //TODO: remove
sorry about that, updated.
Now it's where we left off last time

2021-02-24 23:04 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +    assert(ret == 1);
is ngli_assert ok?  
Please note this code path is only executed when DEBUG_CAPTURE environment variable is set.  
I use ngli_assert because we expect the code to never fail.
Tthe renderdoc sample code uses assert too, see https://renderdoc.org/docs/in_application_api.html.
By default, DEBUG_CAPTURE is not set, so the default code path is independent

2021-02-24 23:05 UTC, jmoguillansky-gpsw commented
we will add part 2 (metal capture support) later, when we actually integrate metal backend

2021-02-25 21:05 UTC, cboesch-gpsw requested changes
please also remove the `tools/capture` depth: just move that in `libnodegl` with the other files

2021-02-25 21:05 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  lib_src += 'tools/capture/renderdoc_capture.c'
you should use `files()` so it always checks if the file exists

2021-02-25 21:05 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  message('enable renderdoc capture: '+enable_renderdoc_capture.to_string())
style: missing space

2021-02-25 21:05 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +  enable_renderdoc_capture = true
you should use a feature system in meson

2021-02-25 21:05 UTC, cboesch-gpsw commented on external/Makefile
> +	ln -snf $< $@
this is no reliable on windows

2021-02-25 21:05 UTC, cboesch-gpsw commented on external/Makefile
> +RENDERDOC_VERSION ?= 1.11
outdated

2021-02-25 21:05 UTC, cboesch-gpsw commented on external/Makefile
> +DEPENDENCIES += pkgconf RenderDoc
if this is unconditional, then it requires documentation updates: `unzip` becomes mandatory

2021-02-25 21:07 UTC, cboesch-gpsw commented on external/Makefile
> +	$(CURL) -L https://renderdoc.org/stable/$(RENDERDOC_VERSION)/RenderDoc_$(RENDERDOC_VERSION)_64.zip -o $@
you can use `$(CURL) -L https://renderdoc.org/stable/$(RENDERDOC_VERSION)/$@ -o $@`

2021-02-25 21:08 UTC, cboesch-gpsw commented on Makefile
> +ifeq ($(TARGET_OS), Windows)
we don't use a space after a comma in `ifeq`

2021-02-25 21:09 UTC, cboesch-gpsw commented on Makefile
> +RenderDoc-install: external-download pkg-config-install $(PREFIX)
this looks broken: it doesn't install anything; external-download should already be triggered

2021-02-25 21:11 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +            DEBUG_CAPTURE = 0;
you could raise the error here

2021-02-25 21:12 UTC, jmoguillansky-gpsw commented on external/Makefile
> +	ln -snf $< $@
it works in wsl, but not mingw.  But renderdoc isn't used on mingw regardless.  
So is that ok if we keep this (for wsl)?

2021-02-25 21:25 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +            DEBUG_CAPTURE = 0;
you mean return with an error code?

2021-02-25 22:23 UTC, jmoguillansky-gpsw commented
> please also remove the `tools/capture` depth: just move that in `libnodegl` with the other files

updated

2021-02-25 22:24 UTC, jmoguillansky-gpsw commented on .gitignore
> +external/RenderDoc*
updated

2021-02-25 22:24 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +static int DEBUG_CAPTURE;
updated

2021-02-25 22:24 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +int init_capture(void) {
updated

2021-02-25 22:24 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +#include <assert.h>
updated

2021-02-25 22:25 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +#include <stdlib.h>
updated

2021-02-25 22:26 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +        return NGL_ERROR_UNSUPPORTED;
updated

2021-02-25 22:26 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +        (pRENDERDOC_GetAPI)dlsym(mod, "RENDERDOC_GetAPI");
updated (removed cast for both dlsym and GetProcAddress)

2021-02-25 22:26 UTC, jmoguillansky-gpsw commented on libnodegl/tools/capture/renderdoc_capture.c
> +    // At init, on windows
updated

2021-02-25 22:27 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  lib_src += 'tools/capture/renderdoc_capture.c'
updated

2021-02-25 22:27 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  message('enable renderdoc capture: '+enable_renderdoc_capture.to_string())
updated

2021-02-25 22:27 UTC, jmoguillansky-gpsw commented on external/Makefile
> +RENDERDOC_VERSION ?= 1.11
updated

2021-02-25 22:28 UTC, jmoguillansky-gpsw commented on external/Makefile
> +DEPENDENCIES += pkgconf RenderDoc
updated.  Up to you if we want it enabled conditionally

2021-02-25 22:28 UTC, jmoguillansky-gpsw commented on external/Makefile
> +	$(CURL) -L https://renderdoc.org/stable/$(RENDERDOC_VERSION)/RenderDoc_$(RENDERDOC_VERSION)_64.zip -o $@
updated

2021-02-25 22:28 UTC, jmoguillansky-gpsw commented on Makefile
> +NODEGL_DEPS=sxplayer-install
updated

2021-02-25 22:28 UTC, jmoguillansky-gpsw commented on Makefile
> +ifeq ($(TARGET_OS), Windows)
updated

2021-02-25 22:35 UTC, jmoguillansky-gpsw commented on Makefile
> +RenderDoc-install: external-download pkg-config-install $(PREFIX)
updated: copy dll

2021-02-25 22:35 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +            DEBUG_CAPTURE = 0;
updated

2021-02-25 23:14 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +      include_directories: [ '..\\external\\RenderDoc' ]
updated

2021-02-25 23:19 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  enable_renderdoc_capture = true
feature system:
enabled: the feature and all its dependencies are required
disabled: disable the feature and don't look for the dependencies
auto: enable the feature if all the dependencies are found.

I'm not sure it's so straightforward to map to this use case. 
Renderdoc doesn't provide a pkg-config file or cmake toolchain file, so it's not a good candidate for meson's dependency system (that's why I use declare_dependency).
What we can do is provide an option to enable_gpu_capture and enable by default.
If the user explicitly disables it, I can disable gpu capture

2021-02-26 00:58 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +  enable_renderdoc_capture = true
updated

2021-02-28 11:57 UTC, cboesch-gpsw commented on libnodegl/renderdoc_capture.c
> +static RENDERDOC_API_1_4_0 *rdoc_api = NULL;
I already said it several times but: no mutable globals

2021-02-28 18:41 UTC, jmoguillansky-gpsw commented on libnodegl/renderdoc_capture.c
> +static RENDERDOC_API_1_4_0 *rdoc_api = NULL;
Its private to this file (static).  What do you propose instead?

2021-02-28 18:43 UTC, ubitux commented on libnodegl/renderdoc_capture.c
> +static RENDERDOC_API_1_4_0 *rdoc_api = NULL;
create a context for your API

2021-03-01 16:39 UTC, jmoguillansky-gpsw commented on libnodegl/renderdoc_capture.c
> +static RENDERDOC_API_1_4_0 *rdoc_api = NULL;
updated.  I also updated the APIs so that they're similar to other node.gl modules

2021-03-01 19:04 UTC, mbouron-gpsw commented on libnodegl/renderdoc_capture.c
> +    void *mod = dlopen("librenderdoc.so", RTLD_LAZY);
I think mod should be part of the context and properly closed (dlclose) in gpu_capture_freep().

2021-03-01 21:29 UTC, jmoguillansky-gpsw commented on libnodegl/renderdoc_capture.c
> +    void *mod = dlopen("librenderdoc.so", RTLD_LAZY);
updated

2021-03-01 23:07 UTC, cboesch-gpsw requested changes

2021-03-01 23:08 UTC, jmoguillansky-gpsw commented on libnodegl/meson_options.txt
> +option('external_dir', type: 'string', value: '../external',
it is set from top level.  It's a parameter.  That's the default value

2021-03-01 23:09 UTC, jmoguillansky-gpsw commented on libnodegl/renderdoc_capture.c
> +    struct gpu_capture_ctx parent;
yes it is.  We will have renderdoc and metal gpu_capture

2021-03-01 23:09 UTC, jmoguillansky-gpsw commented on libnodegl/renderdoc_capture.c
> +#include "gpu_capture.h"
what do you mean?

2021-03-01 23:13 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture.h
> +    int flags;
I want an abstraction for gpu capture on top of renderdoc / metal.

2021-03-01 23:13 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +    s->debug_capture = (getenv("DEBUG_CAPTURE") != NULL);
why is this an issue?  This makes the code easier to read

2021-03-01 23:15 UTC, jmoguillansky-gpsw commented on libnodegl/meson_options.txt
> +option('gpu_capture-renderdoc', type: 'feature', value: 'auto',
I tried to match the style:
e.g. you use gctx-gl (with a dash).
What do you propose instead?

2021-03-01 23:29 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_found = fs.exists('/usr/local/include/renderdoc.h')
I can add a meson option "renderdoc_dir" and set it to /usr/local/include by default ?

2021-03-02 01:02 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +      include_directories: [ external_dir + '/RenderDoc' ]
updated

2021-03-02 01:02 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    'libs': ['dl'],
updated

2021-03-02 15:56 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
Indentation.

2021-03-02 16:06 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    dlclose(s_priv->mod);
Missing null check before calling dlclose().

2021-03-02 16:07 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    FreeLibrary(s_priv->mod);
Does FreeLibrary() handle NULL ? if not please add a check before calling it.

2021-03-02 16:08 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
updated

2021-03-02 16:09 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    ngli_free(s_priv);
`ngli_freep(sp);`

2021-03-02 16:11 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +#include "renderdoc.h"
Depending on the renderdoc version it could either be renderdoc.h or renderdoc_api.h. I think it is up to the build system (meson) to detect which one to use and forward to the source file.

2021-03-02 16:13 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +#include "renderdoc.h"
I think it's a packaging issue.  Ubuntu package comes with renderdoc.h.  Currently I just support windows release package, and ubuntu package.  I will report an issue in renderdoc...

2021-03-02 16:20 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    dlclose(s_priv->mod);
updated

2021-03-02 16:21 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    FreeLibrary(s_priv->mod);
I added a NULL check, though it should never be NULL

2021-03-02 16:25 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    ngli_free(s_priv);
updated

2021-03-02 16:27 UTC, mbouron-gpsw reviewed
Please squash all the commits into "nodegl: add GPU capture support using renderdoc" except "gl: add gpu capture support via renderdoc" so you only have two commits.

2021-03-02 16:27 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +    s->debug_capture = getenv("DEBUG_CAPTURE") != NULL;
`DEBUG_CAPTURE` -> `NGL_GPU_CAPTURE`
and
``` c
const char *var = getenv("DEBUG_CAPTURE");
s->debug_capture = var != NULL && !strcmp(var, "yes");
```

2021-03-02 16:27 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +#ifdef ENABLE_CAPTURE
Please rename `ENABLE_CAPTURE` to `HAVE_GPU_CAPTURE`.

2021-03-02 16:27 UTC, mbouron-gpsw commented on libnodegl/meson.build
> +    'libs': [],
Unneeded chunk.

2021-03-02 16:30 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    FreeLibrary(s_priv->mod);
It should never be NULL but it can happen, gpu_capture_freep() is called unconditionally whether gpu_capture_init() succeeded or not.

2021-03-02 16:32 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +#include "renderdoc.h"
It's not a packaging issue, it's a version issue. Recent versions of renderdoc provide renderdoc_app.h and not renderdoc.h

2021-03-02 16:45 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +#include "renderdoc.h"
old version of renderdoc also has renderdoc_app.h.  I downloaded renderdoc 1.6, it has renderdoc_app.h... are you sure it's not a packaging issue?

2021-03-02 17:14 UTC, jmoguillansky-gpsw commented
> Please squash all the commits into "nodegl: add GPU capture support using renderdoc" except "gl: add gpu capture support via renderdoc" so you only have two commits.

updated

2021-03-02 17:16 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +    s->debug_capture = getenv("DEBUG_CAPTURE") != NULL;
updated

2021-03-02 17:23 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +#ifdef ENABLE_CAPTURE
updated

2021-03-02 17:25 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    'libs': [],
updated

2021-03-02 19:01 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +#include "renderdoc.h"
updated: download binary release package on Linux.  Use renderdoc_app.h always

2021-03-02 20:16 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
gpu_capture_freep() should be called unconditionally.

2021-03-02 20:21 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        if (!s->gpu_capture_ctx) {
`s->debug_capture = 0` should be also added here so gpu_capture_end() in gl_destroy().

2021-03-02 20:28 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    LOG(INFO, "renderdoc capture path: %s\n", s_priv->rdoc_api->GetCaptureFilePathTemplate());
`\n` is not needed after `%s`.

2021-03-02 20:28 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
I only allocate it if debug_capture is 1

2021-03-02 20:30 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        if (!s->gpu_capture_ctx) {
I only allocate if debug_capture

2021-03-02 20:48 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
My point is gpu_capture_end() should only be called if alloc + init was successfull, gpu_capture_freep() should be called to handle the cleanup (init could have suceeded or not), it could here and this is what we usually do for other structure or it could in the init error path of gpu_capture_init().

2021-03-02 20:53 UTC, mbouron-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    s_priv->rdoc_api->EndFrameCapture(NULL, NULL);
Maybe check the return of EndFrameCapture() and log error something like "an error occurred during capture"

2021-03-02 21:07 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
Thats already the case.  If alloc or init are unsuccessul, gl_init will return with an error code which should halt execution.

2021-03-02 23:14 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    s_priv->rdoc_api->EndFrameCapture(NULL, NULL);
updated

2021-03-02 23:14 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    LOG(INFO, "renderdoc capture path: %s\n", s_priv->rdoc_api->GetCaptureFilePathTemplate());
updated

2021-03-03 14:53 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
And gpu_capture_freep() still need to be called otherwise you will leak gpu_capture_ctx..

2021-03-03 15:07 UTC, jmoguillansky-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
So you're saying you still continue execution if gl_init fails?

2021-03-03 15:59 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gctx_gl.c
> +        gpu_capture_freep(&s->gpu_capture_ctx);
gl_destroy() is called unconditionally (whether gl_init() has failed or not) to handle resources cleanup.

2021-03-03 18:17 UTC, cboesch-gpsw requested changes

2021-03-03 18:17 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +      include_directories: [renderdoc_include_dir]
you don't actually need to make an array

2021-03-03 18:40 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +endif
It looks like you can simplify this whole thing with something like:

```meson
renderdoc_dir = get_option('renderdoc_dir')
renderdoc_include_dir = ''
if cc.get_id() == 'msvc'
  renderdoc_include_dir = renderdoc_dir
elif host_system == 'linux'
  renderdoc_include_dir = renderdoc_dir / 'include'
endif
renderdoc_dep = declare_dependency(include_directories: renderdoc_include_dir)
if cc.has_header(renderdoc_include_dir / 'renderdoc_app.h', required: get_option('gpu_capture_renderdoc'))
  lib_src += files('gpu_capture_renderdoc.c')
  conf_data.set10('HAVE_GPU_CAPTURE', true)
  lib_deps += renderdoc_dep
  lib_deps += cc.find_library('dl', required: host_system == 'linux')
endif
```

2021-03-03 18:43 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +endif
if host_system == 'linux'
    lib_deps += cc.find_library('dl', required: true)
  endif

2021-03-03 18:52 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_include_dir = renderdoc_dir + '/include'
I get an error:

libnodegl\meson.build:287:0: ERROR: Include dir C:UsersjmoguillanskyDocuments2020Gitgopro-lib-node.glexternalrenderdoc does not exist.

Seems that when using this operator, meson expects escape characters for slashes e.g. two forward slashes.  
Its simpler overall to keep the code as is

2021-03-03 18:55 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_found = fs.exists(renderdoc_include_dir + '/renderdoc_app.h')
I'm getting a meson setup error:
libnodegl\meson.build:287:0: ERROR: Include dir C:UsersjmoguillanskyDocuments2020Gitgopro-lib-node.glexternalrenderdoc does not exist.

Seems that meson expects the string to have two forward slashes (e.g. use escape chars) when using operator?

2021-03-03 19:16 UTC, jmoguillansky-gpsw commented on Makefile
> +
updated

2021-03-03 19:16 UTC, jmoguillansky-gpsw commented on external/Makefile
> +ifeq ($(TARGET_OS),$(filter $(TARGET_OS),Windows Linux))
updated (with your fix)

2021-03-03 19:16 UTC, jmoguillansky-gpsw commented on external/Makefile
> +endif
applied your fix, thanks

2021-03-03 19:16 UTC, jmoguillansky-gpsw commented on libnodegl/gpu_capture_renderdoc.c
> +    return s;
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +# GPU Capture Options
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_include_dir = renderdoc_dir + '/include'
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_found = fs.exists(renderdoc_include_dir + '/renderdoc_app.h')
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +    renderdoc_include_dir = renderdoc_dir
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +      include_directories: [renderdoc_include_dir]
updated

2021-03-03 19:17 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +endif
nice improvement!  updated

2021-03-03 20:18 UTC, cboesch-gpsw commented on external/Makefile
> +
unrelated

2021-03-03 20:18 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +
I don't think you need this anymore

2021-03-03 21:47 UTC, jmoguillansky-gpsw commented on external/Makefile
> +
updated

2021-03-03 21:47 UTC, jmoguillansky-gpsw commented on libnodegl/meson.build
> +
updated

2021-03-04 16:52 UTC, cboesch-gpsw approved these changes

2021-03-04 16:54 UTC, mbouron-gpsw commented
The branch has been updated with the following changes (no exhaustive list):
- added MinGW supported
- renamed HAVE_GPU_CAPTURE to DEBUG_GPU_CAPTURE (to make it consistent with the other debug variables)
- used meson debug_opts instead of a dedicated gpu_capture_renderdoc option
- added some simplifications in the build system code (Makefile/meson)

2021-03-04 16:54 UTC, mbouron-gpsw approved these changes

2021-03-04 17:19 UTC, merged