pynodegl-utils: use a normalized path that works across all platforms (including WSL)
gopro/gopro-lib-node.gl pull request #201
Opened 2021-02-19 18:40 UTC by jmoguillansky-gpsw

WSL paths are not compatible with Windows paths. 

For example:
WSL path: /mnt/c/Program\ Files
Windows path: C:\Program Files

This code creates a path that is compatible with both WSL and windows (as well as other platforms).

2021-02-19 22:08 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/controller.py
> +from pynodegl_utils.path_util import *
no `import *` in the codebase

2021-02-19 22:09 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        print(local_scene)
no wild debug print please

2021-02-19 22:09 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        local_scene = (path_norm(local_scene))
extra `( )`

2021-02-19 22:10 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +    return p
what exactly breaks with `/`?

Also, isn't python path join actually doing the correct thing?

2021-02-19 22:53 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +    return p
on windows, the path uses forward slashes, e.g. C:\\path\\to\\somewhere
I'm converting it to a path that works in WSL while still working in Windows, e.g. ../relative/path/to/somewhere

2021-02-22 19:04 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/controller.py
> +from pynodegl_utils.path_util import *
updated

2021-02-22 19:04 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        print(local_scene)
updated

2021-02-22 19:04 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        local_scene = (path_norm(local_scene))
updated

2021-02-22 22:10 UTC, ubitux requested changes
You need to explain in the commit description why these path in particular need this

2021-02-22 22:10 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/controller.py
> +import platform
unused import

2021-02-23 09:29 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +def path_join(path, *paths):
you don't need 2 arguments: `*paths` is enough

2021-02-23 09:32 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +    return p
OK; i got it backward initially

2021-02-23 09:33 UTC, cboesch-gpsw requested changes
Please also use `utils` in the prefix.

And don't forget to elaborate in the commit description why you need this for hooks in particular.

2021-02-23 09:34 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +def path_join(path, *paths):
I would not add the path_join() function and instead use the path_norm() function explicitly where necessary. We don't want to hide this processing when joining path unless we want to use this function everywhere instead of os.path().

2021-02-23 18:25 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +def path_join(path, *paths):
python's os.path.join uses a similar signature:
os.path.join(path, *paths)
see: https://docs.python.org/3/library/os.path.html

2021-02-23 18:26 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/controller.py
> +import platform
updated

2021-02-23 18:29 UTC, jmoguillansky-gpsw commented
> You need to explain in the commit description why these path in particular need this

updated

2021-02-23 18:29 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +def path_join(path, *paths):
updated

2021-02-25 09:22 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/path_util.py
> +        p = p.replace('\\','/')
```
>>> pathlib.PureWindowsPath('c:\\Program files/foo\\bar').as_posix()
'c:/Program files/foo/bar'
```

2021-03-10 18:52 UTC, jmoguillansky-gpsw commented
closed for now.
Main motivation for this PR was to support porting ngl-desktop/ngl-control to windows. 
But this has already been done (using python scripts for the hooks).

2021-03-10 18:52 UTC, closed without merging