ngl-desktop: port temp directory to windows
gopro/gopro-lib-node.gl pull request #202
Opened 2021-02-19 18:46 UTC by jmoguillansky-gpsw

/tmp is not valid on windows

2021-02-19 22:07 UTC, cboesch-gpsw commented on ngl-tools/ngl-desktop.c
> +    static TCHAR path_buf[MAX_PATH];
no mutable globals please: `struct ctx` is a better place

2021-02-19 22:08 UTC, cboesch-gpsw commented on ngl-tools/ngl-desktop.c
> +    return path_buf;
`setup_paths` is a good candidate to initialize this

2021-02-20 08:45 UTC, mbouron-gpsw commented on ngl-tools/ngl-desktop.c
> +    DWORD ret_val = GetTempPath(MAX_PATH, path_buf);
`ret_val` is not checked.

2021-02-22 19:01 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    static TCHAR path_buf[MAX_PATH];
updated

2021-02-22 19:01 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    return path_buf;
updated

2021-02-22 19:01 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    DWORD ret_val = GetTempPath(MAX_PATH, path_buf);
updated

2021-02-22 22:08 UTC, ubitux requested changes

2021-02-22 22:08 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +    DWORD ret_val = GetTempPath(MAX_PATH, s->tmp_dir);
`sizeof(s->tmp_dir)`

You also don't need an intermediate variable if you're just going to check its value and not raise it.

2021-02-22 22:08 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +    TCHAR tmp_dir[MAX_PATH];
`GetTempPath` can fill up to `MAX_PATH+1` so you may want to do that

2021-02-22 22:08 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +    assert(ret_val);
No assert in error code path: return `NGL_ERROR_EXTERNAL` or `NGL_ERROR_IO` maybe

2021-02-22 22:08 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +static const char* get_temp_dir(struct ctx *s) {
2 style issues: stick `*` to the function name, and line break before `{` for function names.

You can also have `const struct ctx *`

2021-02-23 00:09 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    DWORD ret_val = GetTempPath(MAX_PATH, s->tmp_dir);
updated.  Can you clarify this comment:

"You also don't need an intermediate variable if you're just going to check its value and not raise it."

2021-02-23 00:10 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    TCHAR tmp_dir[MAX_PATH];
updated

2021-02-23 00:10 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    assert(ret_val);
updated

2021-02-23 00:10 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +static const char* get_temp_dir(struct ctx *s) {
updated

2021-02-23 08:41 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +#include <assert.h>
You forgot to remove this.

2021-02-23 09:39 UTC, mbouron-gpsw commented on ngl-tools/ngl-desktop.c
> +{
Can't we just call directly GetTempPath() here and avoid storing its result in the context ? get_temp_dir() is only used once currently.

2021-02-23 16:19 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +#include <assert.h>
updated

2021-02-23 16:20 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +{
updated

2021-02-23 16:22 UTC, ubitux commented on ngl-tools/ngl-desktop.c
> +    const char *tmp_dir = "/tmp";
this one can be `static const`

2021-02-23 16:23 UTC, ubitux reviewed
Please `tools/desktop` as commit message prefix, and aside from the cosmetic, LGTM

2021-02-23 16:27 UTC, jmoguillansky-gpsw commented on ngl-tools/ngl-desktop.c
> +    const char *tmp_dir = "/tmp";
updated

2021-02-23 16:27 UTC, jmoguillansky-gpsw commented
> Please `tools/desktop` as commit message prefix, and aside from the cosmetic, LGTM

updated

2021-02-23 16:42 UTC, mbouron-gpsw approved these changes
LGTM.

2021-02-23 16:50 UTC, cboesch-gpsw approved these changes

2021-02-23 17:38 UTC, mbouron-gpsw approved these changes

2021-02-23 17:40 UTC, merged