pynodegl-utils: set dll search directories
gopro/gopro-lib-node.gl pull request #205
Opened 2021-02-19 19:04 UTC by jmoguillansky-gpsw

Currently, when loading a python module, the DLL search path is set to the directory containing the python module.
It doesn't search the directories specified in PATH environment variable.
see https://bugs.python.org/issue43173
With this change, we add the directories in PATH environment variable, along with the venv/Scripts folder as DLL search paths on Windows.  This allows us to avoid copying the DLL to multiple directories

2021-02-19 22:24 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +    prefix = pathlib.Path(__file__).parent.absolute().joinpath('../../../venv')
hum. I don't think this is acceptable

2021-02-19 22:55 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +    prefix = pathlib.Path(__file__).parent.absolute().joinpath('../../../venv')
you mean hardcoding venv?  how can we pass the prefix variable?  maybe as an environment variable?

2021-02-22 19:10 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +    prefix = pathlib.Path(__file__).parent.absolute().joinpath('../../../venv')
updated.

2021-02-22 22:01 UTC, ubitux requested changes

2021-02-22 22:01 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +import pathlib
pathlib is unused

2021-02-22 22:01 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +
missing 2nd line break

2021-02-22 22:01 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
Can you explain in the commit description the reason why Python doesn't do it itself?

2021-02-22 22:03 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
it's already explained in the link
https://bugs.python.org/issue43173

In 3.8+, the search path for the dependent DLLs of a normally imported extension module includes the following directories:

    * the loaded extension module's directory
    * the application directory (e.g. that of python.exe)
    * the user DLL search directories that get added by 
      SetDllDirectory() and AddDllDirectory(), such as with 
      os.add_dll_directory()
    * %SystemRoot%\System32

Note that the above list does not include the current working directory or %PATH% directories.

2021-02-22 22:16 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
Unless I'm mistaken, nothing explains here *why* `PATH` is not honored.

2021-02-22 22:19 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
the Python developers explained in the issue tracker that it doesn't honor PATH environment variable when searching for dlls

2021-02-22 22:20 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +import pathlib
updated

2021-02-22 22:21 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +
updated

2021-02-22 22:22 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
Yeah. But **why**?

2021-02-22 22:26 UTC, ubitux requested changes

2021-02-22 22:26 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +    env_path = os.getenv("PATH").split(';')
consistent quoting please

2021-02-22 22:26 UTC, ubitux commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +        if os.path.exists(p):
you can use `op`

2021-02-22 22:26 UTC, ubitux commented
commit message: please use `utils:` as prefix

2021-02-22 22:53 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +    env_path = os.getenv("PATH").split(';')
updated

2021-02-22 22:53 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +        if os.path.exists(p):
updated

2021-02-22 22:54 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
> commit message: please use `utils:` as prefix

updated

2021-02-22 23:21 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
> Yeah. But **why**?

I don't know, need to ask the Python developers

2021-02-23 04:37 UTC, jmoguillansky-gpsw commented
> commit message: please use `utils:` as prefix

Updated

2021-02-23 09:56 UTC, cboesch-gpsw requested changes
You're doing this dll hook at the import time of the `ngl-test` program: why at import time and not in its main? This code could be triggered as soon as the module gets imported (by side effect or not). What's the goal here? You want it only for `ngl-test` or utils wide?

2021-02-23 18:02 UTC, jmoguillansky-gpsw commented
> You're doing this dll hook at the import time of the `ngl-test` program: why at import time and not in its main? This code could be triggered as soon as the module gets imported (by side effect or not). What's the goal here? You want it only for `ngl-test` or utils wide?

You're right, we want it utils wide.
I will try this suggestion...

2021-02-23 19:17 UTC, jmoguillansky-gpsw commented on pynodegl-utils/pynodegl_utils/tests/__init__.py
> +            os.add_dll_directory(p)
my guess is that it simplifies the configuration: one less variable to consider (and which the user may modify).  
If we look at the typical approach currently used in Python, all the dlls seem to be duplicated in the python module folder.
For example, for PySide2 (python Qt bindings), all the Qt DLLs are stored twice: once in system's Qt installation and once in PySide2

Maybe it's better to just have duplicate copies of the DLL for now since that seems to be consistent with Python's current approach.
For long term we can consider merging pynodegl and pynodegl-utils into one module (pynodegl) to simplify install, and this way we'll have less duplicate modules.

2021-03-01 13:37 UTC, jbelaston-gpsw reviewed
Is this change needed for easy debug ?

2021-03-03 22:53 UTC, jmoguillansky-gpsw commented
> Is this change needed for easy debug ?

No it's to avoid duplicate copies of dlls

2021-05-21 15:18 UTC, closed without merging