ci: (windows) misc
gopro/gopro-lib-node.gl pull request #207
Opened 2021-02-19 19:29 UTC by jmoguillansky-gpsw

Split mingw and msvc tests into separate workflows
Improve vcpkg caching mechanism

2021-02-19 22:20 UTC, cboesch-gpsw commented
Isn't this going to break the badge in the README?

2021-02-19 22:21 UTC, cboesch-gpsw commented on .github/workflows/ci_msvc.yml
> +          # see https://github.com/mesonbuild/meson/issues/8329
please do not slip in changes in a code move: preserve the content of the rules exactly the same. These changes must be discussed separately

2021-02-19 22:41 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_msvc.yml
> +          # see https://github.com/mesonbuild/meson/issues/8329
I'm using the built-in vcpkg but it's on C drive.  The project is on D drive.  There's a bug in meson where the dependencies need to be on the same drive.

2021-02-20 10:14 UTC, cboesch-gpsw commented on .github/workflows/ci_msvc.yml
> +          # see https://github.com/mesonbuild/meson/issues/8329
That's not what my remark is about: you're hiding functional changes in a move commit

2021-02-22 19:12 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_msvc.yml
> +          # see https://github.com/mesonbuild/meson/issues/8329
it's not only a move commit, see the commit message.  But I will split it up into atomic commits like you prefer

2021-03-01 13:47 UTC, jbelaston-gpsw requested changes

2021-03-01 13:47 UTC, jbelaston-gpsw commented on .github/workflows/ci_msvc.yml
> +          # see https://github.com/mesonbuild/meson/issues/8329
+1
Yeah I think it's really difficult here to do the review of a code which has been moved and updated... :disappointed: 
So, please, here my proposal :slightly_smiling_face: :
- one commit only for the move (without any other change)
- then another one for the change

2021-03-10 18:59 UTC, jmoguillansky-gpsw commented
closed, already merged in a different PR

2021-03-10 18:59 UTC, closed without merging