ci: (linux) misc improvements
gopro/gopro-lib-node.gl pull request #209
Opened 2021-02-19 22:42 UTC by jmoguillansky-gpsw

Use matrix to consolidate common code across jobs

2021-02-20 10:16 UTC, cboesch-gpsw requested changes
One change at a time please: the matrix change is completely unrelated to the addition of renderdoc

2021-02-22 21:12 UTC, jmoguillansky-gpsw commented
> One change at a time please: the matrix change is completely unrelated to the addition of renderdoc

updated, I will add renderdoc and ninja in the other PR when it's actually used

2021-02-22 21:59 UTC, ubitux requested changes

2021-02-22 21:59 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +    - name: Install Dependencies
This looks unrelated

2021-02-22 21:59 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +          libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
This looks unrelated

2021-02-22 21:59 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +        export PKG_CONFIG_PATH=$PWD/venv/lib/pkgconfig
This looks unrelated

2021-02-22 21:59 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +        export PKG_CONFIG_PATH=$PWD/venv/lib/pkgconfig
This looks unrelated

2021-02-22 22:16 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +    - name: Install Dependencies
updated, I dropped this change for now

2021-02-22 22:16 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +          libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
updated, I dropped this change for now

2021-02-22 22:17 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +        export PKG_CONFIG_PATH=$PWD/venv/lib/pkgconfig
updated, I dropped this change for now

2021-02-22 22:17 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +        export PKG_CONFIG_PATH=$PWD/venv/lib/pkgconfig
updated, I dropped this change for now

2021-02-22 22:21 UTC, ubitux requested changes
Please change the commit message to "ci/linux: simplify code using matrix"; we never use this "( ... )" form.

Also, again, please stop trying to slip in unrelated changes all the time, it delays the review process unnecessarily. Every unrelated change is a potential never ending separated discussion: leave them out.

2021-02-22 22:21 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +          - backend: "opengles"
can you explicit the `2`?

2021-02-22 22:21 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +            run_tests_command: "DEBUG=yes DEBUG_GL=yes make tests"
you removed `-k -j$(($(nproc)+1))`

2021-02-22 22:21 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +            run_tests_command: "MESA_GLES_VERSION_OVERRIDE=2.0 DEBUG=yes DEBUG_GL=yes make tests TESTS_SUITE=opengles"
you removed `-k -j$(($(nproc)+1))`

2021-02-22 22:34 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +          - backend: "opengles"
sorry I don't understand the question

2021-02-22 22:35 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +            run_tests_command: "DEBUG=yes DEBUG_GL=yes make tests"
I will remove this change and we can discuss it separately.  

The motivation for these changes:
The reason for removing -j is because the log output gets scrambled
We can still build targets using multiple threads, but if we build multiple targets in parallel, it scrambles the log output
As far as removing the -k, I think we should catch the errors, not keep going?

2021-02-22 22:37 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +          - backend: "opengles"
This is specifically testing gles**2**, not just gles

2021-02-22 22:41 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +            run_tests_command: "DEBUG=yes DEBUG_GL=yes make tests"
> The reason for removing -j is because the log output gets scrambled

Yeah but:
1. it's unrelated
2. jobbed `make` is useful for parallel downloading of external and various other build exec
3. why would you do it only for linux and not all the other
4. it needs a discussion and explanation when doing such a change

> As far as removing the -k, I think we should catch the errors, not keep going?

Same as previously (unrelated, not exclusive to linux, separated discussion,)

`-k` does catch the error, but it still tries all code paths: the reason we have this is because the tests were previously running through make, and you wanted to run them all before reporting any error. This might not be relevant anymore so it might indeed be relevant to remove them... separately, with a dedicated explanation such as the one I just provided.

2021-02-22 22:42 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +            run_tests_command: "MESA_GLES_VERSION_OVERRIDE=2.0 DEBUG=yes DEBUG_GL=yes make tests TESTS_SUITE=opengles"
updated, I removed this change, we can discuss separately

2021-02-22 22:44 UTC, ubitux commented on .github/workflows/ci_linux.yml
> +        ${{ matrix.run_tests_command }}
Can you be consistent with your use of `${{ X }}` vs `${{X}}`? Also please don't forget my comment about the commit message.

2021-02-22 22:46 UTC, jmoguillansky-gpsw commented on .github/workflows/ci_linux.yml
> +        ${{ matrix.run_tests_command }}
thanks, updated

2021-02-23 10:03 UTC, cboesch-gpsw approved these changes

2021-02-23 10:05 UTC, mbouron-gpsw approved these changes

2021-02-23 10:05 UTC, merged