utils: remove the use of a dedicated process to handle scripts live changes
gopro/gopro-lib-node.gl pull request #219
Opened 2021-03-02 15:12 UTC by mbouron-gpsw

2021-03-03 16:19 UTC, cboesch-gpsw requested changes

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +            self._set_reloaded()
These 2 are swapped compared to below. Is this on purpose?

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +        self._reloaded_cond = QtCore.QWaitCondition()
Would it make sense to rename `_query_cond` and `_reloaded_cond` to respectively `_query_count_cond` and `_reloading_cond` so that we know what they are associated with precisely?

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/filetracker.py
> +        self._start_modules = set(sys.modules.keys())
not a fan of the implicit convert from `dict_keys` to `set`; can you explicit the `set()` here as well?

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/filetracker.py
> +        self.modulelist = set()
It's really confusing to have a module list managed by the *file* tracker. Can you rename the module to something more appropriate? `ResourceTracker`, `StateTracker`, or simply `Tracker`. Or anything else really, but not "File".

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +        self._modules = set(modulelist)
it's already a `set()`, right?

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/ui/main_window.py
> +        self._scripts_mgr.update_filelist(ret['filelist'])
Why this change? Can it be extracted earlier?

2021-03-03 16:19 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                    self.done.emit(session_id, self._scene_id, time.time() - start_time)
Can you move the following in a dedicated method that take `fname` as argument?
```python
                    self.sendingScene.emit(session_id, self._scene_id)
                    try:
                        self._hooks_caller.scene_change(session_id, fname, cfg)
                    except Exception as e:
                        self.error.emit(session_id, 'Error while sending scene: %s' % str(e))
                        return
                    self.done.emit(session_id, self._scene_id, time.time() - start_time)
```

This will prevent desync between the two blocks, typically you forgot to include `self.sendingScene.emit(...)`  in the Windows path (or is it on purpose?)

2021-03-03 16:19 UTC, cboesch-gpsw commented on Makefile
> +# We do not pull the requirements on Windows/MinGW because of various issues:
"Windows (for both MSVC and MinGW)"

2021-03-03 16:21 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/filetracker.py
> +        new_modules = sys.modules.keys() - self._start_modules
not a fan of the implicit convert from `dict_keys` to `set`; can you explicit the `set()` here as well?

2021-03-03 16:30 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +        self._reloaded_cond = QtCore.QWaitCondition()
Ok for `_query_count_cond`, regarding `_reloaded_cond` it makes more sense to me to call it this way. You wait for the reloaded condition.

2021-03-03 16:33 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +        self._modules = set(modulelist)
I followed what was done in set_filelist(). It supposed to be `set()` but it does not prevent someone to call it with a list.

2021-03-03 16:34 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/ui/main_window.py
> +        self._scripts_mgr.update_filelist(ret['filelist'])
This code is executed in parralel and the query does not rely on a subprocess anymore meaning that if the underlying script has already been loaded, its file list will be empty.

2021-03-03 16:36 UTC, mbouron-gpsw commented on Makefile
> +# We do not pull the requirements on Windows/MinGW because of various issues:
The issues described bellow are only on MinGW (except the one described for ngl-control).

2021-03-03 18:46 UTC, cboesch-gpsw commented on Makefile
> +# We do not pull the requirements on Windows/MinGW because of various issues:
Ah. Maybe explicit MinGW only then?

2021-03-03 20:29 UTC, mbouron commented on pynodegl-utils/pynodegl_utils/com.py
> +from PySide2 import QtCore
Fixed.

2021-03-03 20:29 UTC, mbouron commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                    self.done.emit(session_id, self._scene_id, time.time() - start_time)
Done.

2021-03-03 20:30 UTC, mbouron commented on pynodegl-utils/pynodegl_utils/filetracker.py
> +        new_modules = sys.modules.keys() - self._start_modules
Fixed.

2021-03-03 20:32 UTC, mbouron commented on Makefile
> +# We do not pull the requirements on Windows/MinGW because of various issues:
Ok. Updated.

2021-03-04 08:17 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +            self._set_reloaded()
Fixed.

2021-03-04 08:44 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/scriptsmgr.py
> +        self._reloaded_cond = QtCore.QWaitCondition()
Actually renamed both. I don't really care (even though it makes more sense to me to use `_reloaded_cond`).

2021-03-04 08:48 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/filetracker.py
> +        self.modulelist = set()
Done in a separate commit.

2021-03-04 09:29 UTC, cboesch-gpsw approved these changes

2021-03-04 09:39 UTC, merged