ci/doc: update vcpkg commit id to the latest known revision working for shaderc
gopro/gopro-lib-node.gl pull request #235
Opened 2021-03-12 09:26 UTC by mbouron-gpsw

56136ffae69a4a7f8b9cd5452713925417d47367 is preceding
f6a877255e8b648eeec18ba6efb015e601f2286f that disabled the shared build
of shaderc.

2021-03-12 15:52 UTC, jmoguillansky-gpsw commented
That works too.  Basically what I did is git log ports/shaderc and then reverted only the ports/shaderc folder to a previous commit.  I think both approaches will get the exact same result?

2021-03-12 15:54 UTC, jmoguillansky-gpsw approved these changes
Looks ok to me.  I think the change in commit id is equivalent as far as shaderc is concerned?

2021-03-15 14:03 UTC, cboesch-gpsw requested changes
Change LGTM but please adjust the 2 following things in the commit message:
1. `ci/doc` → `ci,doc` (we usually use `/` to represent a sub-category while `,` separates independent ones). Alternatively we could use `ci: doc:` like the kernel does (AFAICT) but I kinda of prefer the comma, which I used in the past (db9941461e556ffbd196326bf210e7f249a0a512, ccd7731f999004517b805eb9606e0a2d5f5c61ce) and you as well apparently (9acb0473fe0a04720ed9a6234d0c391c058edbc4, 956429041e7558ddd1c490019ac828a7385734dd).
2. please specify how the current hash was chosen initially

2021-03-15 16:26 UTC, mbouron-gpsw commented
> Change LGTM but please adjust the 2 following things in the commit message:
> 
>     1. `ci/doc` → `ci,doc` (we usually use `/` to represent a sub-category while `,` separates independent ones). Alternatively we could use `ci: doc:` like the kernel does (AFAICT) but I kinda of prefer the comma, which I used in the past ([db99414](https://github.com/gopro/gopro-lib-node.gl/commit/db9941461e556ffbd196326bf210e7f249a0a512), [ccd7731](https://github.com/gopro/gopro-lib-node.gl/commit/ccd7731f999004517b805eb9606e0a2d5f5c61ce)) and you as well apparently ([9acb047](https://github.com/gopro/gopro-lib-node.gl/commit/9acb0473fe0a04720ed9a6234d0c391c058edbc4), [9564290](https://github.com/gopro/gopro-lib-node.gl/commit/956429041e7558ddd1c490019ac828a7385734dd)).
> 
>     2. please specify how the current hash was chosen initially

Done.

2021-03-15 16:36 UTC, cboesch-gpsw approved these changes

2021-03-15 16:41 UTC, jmoguillansky-gpsw commented
> Change LGTM but please adjust the 2 following things in the commit message:
> 
> 1. `ci/doc` → `ci,doc` (we usually use `/` to represent a sub-category while `,` separates independent ones). Alternatively we could use `ci: doc:` like the kernel does (AFAICT) but I kinda of prefer the comma, which I used in the past ([db99414](https://github.com/gopro/gopro-lib-node.gl/commit/db9941461e556ffbd196326bf210e7f249a0a512), [ccd7731](https://github.com/gopro/gopro-lib-node.gl/commit/ccd7731f999004517b805eb9606e0a2d5f5c61ce)) and you as well apparently ([9acb047](https://github.com/gopro/gopro-lib-node.gl/commit/9acb0473fe0a04720ed9a6234d0c391c058edbc4), [9564290](https://github.com/gopro/gopro-lib-node.gl/commit/956429041e7558ddd1c490019ac828a7385734dd)).
> 2. please specify how the current hash was chosen initially

how the current hash was chosen:
git log -- ports/shaderc

2021-03-15 16:47 UTC, mbouron-gpsw commented
> Looks ok to me. I think the change in commit id is equivalent as far as shaderc is concerned?

Yes, it is equivalent for shaderc.

2021-03-15 16:48 UTC, merged