ngl-tools: fix memory leak
gopro/gopro-lib-node.gl pull request #257
Opened 2021-03-25 00:12 UTC by jmoguillansky-gpsw

2021-03-25 08:31 UTC, mbouron-gpsw commented on ngl-tools/opts.c
> +    if (backends)
You can remove this check, free handle NULL ptrs.

2021-03-25 08:34 UTC, mbouron-gpsw commented
Can you also reword the commit message to `tools/opts: fix memory leak of backends array` ?
Other than this reword and the other remark regarding the NULL check before calling free(), LGTM, thanks.

2021-03-25 09:02 UTC, mbouron-gpsw commented on ngl-tools/opts.c
> +    if (backends)
Also ngl_backends_freep() should be used instead of free().

2021-03-25 17:17 UTC, jmoguillansky-gpsw commented on ngl-tools/opts.c
> +    if (backends)
updated

2021-03-25 17:18 UTC, jmoguillansky-gpsw commented
> Can you also reword the commit message to `tools/opts: fix memory leak of backends array` ?
> Other than this reword and the other remark regarding the NULL check before calling free(), LGTM, thanks.

updated

2021-03-26 09:55 UTC, cboesch-gpsw requested changes

2021-03-26 15:01 UTC, jmoguillansky-gpsw commented on ngl-tools/opts.c
> +    }
is this ok?

static int get_backend(const char *id)
{
    if (!strcmp(id, "auto"))
        return NGL_BACKEND_AUTO;

    int nb_backends;
    struct ngl_backend *backends = NULL;
    int ret = ngl_backends_probe(NULL, &nb_backends, &backends);
    if (ret < 0)
        goto end;
    for (int i = 0; i < nb_backends; i++) {
        if (!strcmp(backends[i].string_id, id)) {
            ngl_backends_freep(&backends);
            return ret;
        }
    }
    ret = NGL_ERROR_NOT_FOUND;
end:
    ngl_backends_freep(&backends);
    return ret;
}

2021-03-26 15:44 UTC, mbouron-gpsw commented on ngl-tools/opts.c
> +    }
```c
int ret = ngl_backends_probe(NULL, &nb_backends, &backends);
if (ret < 0)
    return ret;
```
This part can stay the same (no need to goto end), if ngl_backends_probe() fails, the user does not have to handle the cleanup of the backends array.

Moreover, it could also be simpler to just add a call to ngl_backends_freep(&backends); before returning if the backend is found, what do you think ?

2021-03-26 15:45 UTC, jmoguillansky-gpsw commented on ngl-tools/opts.c
> +    }
if the command fails, backends won't be allocated?

2021-03-26 15:51 UTC, jmoguillansky-gpsw commented on ngl-tools/opts.c
> +    }
updated

2021-03-26 15:57 UTC, mbouron-gpsw commented on ngl-tools/opts.c
> +    }
> if the command fails, backends won't be allocated?

if ngl_backends_probe() returns an error, the cleanup is done internally.

2021-03-26 16:45 UTC, cboesch-gpsw approved these changes

2021-03-26 16:47 UTC, merged