pgcraft: simplify attribute and buffer binding logic
gopro/gopro-lib-node.gl pull request #325
Opened 2021-10-17 20:17 UTC by mbouron-gpsw

Depends on https://github.com/gopro/gopro-lib-node.gl/pull/323.

2021-10-18 13:43 UTC, cboesch-gpsw commented on libnodegl/pgcraft.c
> +        s->next_bindings[BIND_ID(NGLI_PROGRAM_SHADER_COMP, NGLI_BINDING_TYPE_TEXTURE)] = NULL;
Aren't you restoring a chunk you removed from `pgcraft-image`?

2021-10-18 13:44 UTC, cboesch-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +#include "log.h"
You're not adding any logging

2021-10-18 13:44 UTC, cboesch-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +
extra line break

2021-10-18 14:07 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +
Fixed.

2021-10-18 14:08 UTC, mbouron-gpsw commented
> In the 2nd commit:
> 
> "even though the context does not support ..." → "even when the context does not support ..."

Fixed with "even if" (to make it consistent with the other commit.

2021-10-19 09:01 UTC, cboesch-gpsw requested changes
Thanks, I really like this PR. My comments are mostly cosmetics.

2021-10-19 09:01 UTC, cboesch-gpsw commented on libnodegl/pgcraft.c
> +    int base_location = s->next_in_locations[stage];
can be `const` now :)

2021-10-19 11:51 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +        struct pipeline_buffer_desc *buffer_desc = &buffer_descs[i];
Done.

2021-10-19 11:51 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +        GLuint block_index = ngli_glGetUniformBlockIndex(gl, s_priv->id, buffer_desc->name);
Done.

2021-10-19 11:51 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl.c
> +            GLuint block_index = ngli_glGetUniformBlockIndex(gl, pid, name);
Done.

2021-10-19 11:51 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl_utils.c
> +        struct pipeline_attribute_desc *attribute_desc = &attribute_descs[i];
Done.

2021-10-19 20:44 UTC, cboesch-gpsw commented on libnodegl/backends/gl/program_gl.c
> +        if (gl->features & NGLI_FEATURE_PROGRAM_INTERFACE_QUERY) {
Thanks, I actually totally forgot that we weren't dumb enough to set binding=0 as default. Your explanation clarifies the combination, thanks.

For the info updating, I'm not so sure, I think it's a strength that the info could be accessed read-only, it clarifies the direction of the flow.

2021-10-21 09:50 UTC, mbouron-gpsw commented on libnodegl/backends/gl/program_gl.c
> +        if (gl->features & NGLI_FEATURE_PROGRAM_INTERFACE_QUERY) {
I prefer these information to stay in sync in this specific case (non explicit bindings) since we are modifying them at the OpenGL shader level anyway.

2021-10-21 09:59 UTC, merged