Hooks improvements
gopro/gopro-lib-node.gl pull request #332
Opened 2021-11-03 20:06 UTC by mbouron-gpsw

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                )
nitpick: this can probably be on the same line

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            info = self._hooks_caller.get_session_info(session['sid'])
What if you get 2 close scene change signals?

| Thread 0 | Thread 1 |
|---|---|
| enter `submit_session_info()` | |
| session = S0 | |
| emit process | |
| | enter `submit_session_info()` |
| | session = S1 |
| | emit process |
| enter `_run()` | |
| read session = S1 ⚠️ | |
| calling `get_session_info(S1)` | |
| | enter `_run()` |
| | read session = S1 |
| | calling `get_session_info(S1)` ⚠️ |

1. The first warning is because it should have read S0
2. the impact of reading twice S1 means that we might have concurrent `get_session_info()` on the same session

Did I miss something?

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                removed_sessions.append(session_id)
Maybe just:

```python
removed_sessions = [sid for sid in self._sessions_cache.keys() if sid not in sessions]
```
?

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            del self._sessions_cache[session_id]
Aren't you loosing the session `enabled` state here? For example, let's say you disable one of your android device because its connection is bad; it's appearing on and off in your device list. If it does that once between refresh events, isn't it going to be re-enabled?

I added a sample test in `hooks_view.py` to test this particular scenario. I realize the test is currently broken on master so here is a quick patch:

```diff
diff --git a/pynodegl-utils/pynodegl_utils/ui/hooks_view.py b/pynodegl-utils/pynodegl_utils/ui/hooks_view.py
index cacbed80..8bc6b176 100644
--- a/pynodegl-utils/pynodegl_utils/ui/hooks_view.py
+++ b/pynodegl-utils/pynodegl_utils/ui/hooks_view.py
@@ -126,14 +126,14 @@ class HooksView(QtWidgets.QWidget):
         self._auto_refresh_btn = QtWidgets.QCheckBox('Automatic refresh')
         self._auto_refresh_btn.setChecked(True)

-        spawn_view = _SpawnView(config)
-
         hbox = QtWidgets.QHBoxLayout()
         hbox.addStretch()
         hbox.addWidget(self._auto_refresh_btn)

         serial_layout = QtWidgets.QVBoxLayout(self)
-        serial_layout.addWidget(spawn_view)
+        if config:
+            spawn_view = _SpawnView(config)
+            serial_layout.addWidget(spawn_view)
         serial_layout.addLayout(hbox)
         serial_layout.addWidget(self._view)

@@ -242,7 +242,7 @@ if __name__ == '__main__':

         def __init__(self):
             super().__init__()
-            self._hooks_view = HooksView(DummyHooksCaller())
+            self._hooks_view = HooksView(DummyHooksCaller(), config=None)
             action_btn = QtWidgets.QPushButton('Action!')
             action_btn.clicked.connect(self._do_action)
             layout = QtWidgets.QVBoxLayout()
```

Try to use that to see what I mean (`python pynodegl-utils/pynodegl_utils/ui/hooks_view.py`): in that test if you uncheck some device(s), you'll see that when they show up again after a while their state is memorized.

This brings me to my 2nd point: that test is going to be annoying to adjust after your changes, so you may want to either rewrite it differently or just ditch it. It was actually very useful during development for simulating these kind of crazy scenarios.

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            s = dict(
better name maybe? `new_session` or something

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        if session:
I'd prefer the error to be the exception, so `if not session: return`, if you don't mind.

2021-11-03 22:38 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            self.success.emit(session, info)
can we have that emit out of the try loop? it should be clear that the exception is here to catch an issue with `get_session_info()` and not this, which isn't supposed to fail

2021-11-04 08:13 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            with tempfile.TemporaryDirectory() as td:
Done.

2021-11-04 08:13 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                                                 mode='w', newline='\n', delete=False) as fp:
Done.

2021-11-04 08:15 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                )
Done.

2021-11-04 08:17 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            s = dict(
Done.

2021-11-04 08:19 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            self.success.emit(session, info)
Done.

2021-11-04 08:24 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                removed_sessions.append(session_id)
Done.

2021-11-04 08:31 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            info = self._hooks_caller.get_session_info(session['sid'])
This scenario can't happen, one SessionInfoWorker is created per session (thread), so one SessionInfoWorker will always receive the same session ("S0" for Thread 0, "S1" for Thread 1. The session worker API is misleading though, the session_id should be passed to SessionInfoWorker constructor and submit_session_info() should not take any additional parameter and should be renamed.

2021-11-04 09:33 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            info = self._hooks_caller.get_session_info(session['sid'])
Ah I see, makes sense. I'll wait for the rename to resolve the conversation. Thanks.

2021-11-04 09:43 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            info = self._hooks_caller.get_session_info(session['sid'])
The SessionInfoWorker API has been updated.

2021-11-04 09:46 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +        if session:
Done.

2021-11-04 10:39 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            info = self._hooks_caller.get_session_info(session['sid'])
Looking at it again, we can have concurrent `get_session_info()` calls on the same session though, right?

2021-11-04 12:13 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +            del self._sessions_cache[session_id]
Tests have been fixed in a separate commit and properly ported in the latest commit on this PR.
The `enabled` state is now preserved by storing it in the HooksController._sessions_state dictionary.

2021-11-04 13:21 UTC, cboesch-gpsw requested changes
A few more cosmetics but LGTM otherwise

2021-11-04 13:21 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                sid=f'{caller_id}:{session_id}'
missing spaces

2021-11-04 13:21 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> +            return sessions
```python
return {key: self._full_data[key] for key in keys}
```

2021-11-04 13:21 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> +            action_btn.clicked.connect(self._refresh)
There is already the refresh checkbox so you can just ditch the button IMO

2021-11-04 13:21 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> -                status = f"applied action at {time.time()}" if data_row['checked'] else ''
`import time` should not be needed anymore then

2021-11-04 13:26 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> +            return sessions
Fixed.

2021-11-04 13:27 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> +            action_btn.clicked.connect(self._refresh)
The button gives more control over the frequency of refresh, plus it tests the HooksController.refresh_sessions() api directly. It doesn't hurt to keep it.

2021-11-04 13:28 UTC, mbouron-gpsw commented on pynodegl-utils/pynodegl_utils/hooks.py
> +                sid=f'{caller_id}:{session_id}'
Fixed.

2021-11-04 13:29 UTC, cboesch-gpsw commented on pynodegl-utils/pynodegl_utils/ui/hooks_view.py
> +            action_btn.clicked.connect(self._refresh)
OK

2021-11-04 13:50 UTC, cboesch-gpsw approved these changes

2021-11-04 14:32 UTC, merged