Glcontext cleanups
gopro/gopro-lib-node.gl pull request #360
Opened 2021-12-19 16:07 UTC by mbouron-gpsw

2021-12-19 16:49 UTC, cboesch-gpsw requested changes

2021-12-19 16:49 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glcontext.c
> +        ngli_assert(0);
`ngli_assert(ret >= 0)`?

2021-12-19 16:49 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glcontext.c
> +            break;
you may want to break if the error is the same as the previous loop to avoid an infinite loop

2021-12-19 17:07 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glcontext.c
> +            break;
Switched to a for loop.

2021-12-19 17:08 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glcontext.c
> +        ngli_assert(0);
Done.

2021-12-19 17:43 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glcontext.c
> +        ret = -1;
you may want to `return NGL_ERROR_GRAPHICS_GENERIC` and do something prettier in `gpu_ctx_gl.c` (not a blocking comment)

2021-12-19 17:43 UTC, cboesch-gpsw approved these changes

2021-12-20 10:00 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glcontext.c
> +        ret = -1;
Done.

2021-12-21 09:09 UTC, merged