gput_ctx_gl: reset depth/stencil write masks before calling glClear()
gopro/gopro-lib-node.gl pull request #362
Opened 2021-12-27 19:38 UTC by mbouron-gpsw

The OpenGL documentation states:

> The pixel ownership test, the scissor test, dithering, and the buffer
writemasks affect the operation of glClear.

Without this patch, rendertargets can end up partially cleared if the
depth/stencil write masks are not reset to their default values.

Related to bdb5f389560d3e81a5a1019a6c0b74013f0fbc09.

2022-01-03 15:30 UTC, ubitux requested changes

2022-01-03 15:30 UTC, ubitux commented on tests/depth_stencil.py
> +#!/usr/bin/env python
unneeded shebang

2022-01-03 15:30 UTC, ubitux commented on tests/depth_stencil.py
> +# Copyright 2020 GoPro Inc.
2021 (or 2022)

2022-01-03 15:30 UTC, ubitux commented on tests/depth_stencil.py
> +    return render
note to self: this needs to be adjusted in my branches if upstreamed before my other PRs

2022-01-03 15:30 UTC, ubitux commented on tests/meson.build
> +  ]
Both tests are passing for me with your fix reverted. They're not supposed to be related?

2022-01-03 17:16 UTC, mbouron-gpsw commented on tests/depth_stencil.py
> +#!/usr/bin/env python
Removed.

2022-01-03 17:31 UTC, mbouron-gpsw commented on tests/meson.build
> +  ]
They are related, I updated them to use 2 keyframes. The tests are now failing if the first commit is reverted.
The issue can also be reproduced with `ngl-python -u tests/depth_stencil.py depth_stencil_depth` (`-u` is mandatory to reproduce the issue).

2022-01-03 17:32 UTC, mbouron-gpsw commented on tests/depth_stencil.py
> +# Copyright 2020 GoPro Inc.
Done.

2022-01-04 11:13 UTC, cboesch-gpsw requested changes

2022-01-04 11:13 UTC, cboesch-gpsw commented on tests/depth_stencil.py
> +# Copyright 2022 GoPro Inc.
missing '#' at the beginning

2022-01-04 11:52 UTC, cboesch-gpsw approved these changes

2022-01-04 12:20 UTC, merged