gpu_ctx_gl: misc cleanups
gopro/gopro-lib-node.gl pull request #367
Opened 2022-01-04 16:32 UTC by mbouron-gpsw

2022-01-04 23:27 UTC, cboesch-gpsw requested changes

2022-01-04 23:27 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
`create_rendertarget()` calls `ngli_rendertarget_freep()` in case of failure, but you do have them in this codepath as well (under the `fail:` label).

The code looks a bit fragile too, in particular around this:
```c
s_priv->default_rt = rt;
s_priv->default_rt_load = rt_load;
```

If it was possible to fail after these assignments (it can't right now fortunately), then `ngli_rendertarget_freep(&rt)` and `ngli_rendertarget_freep(&rt_load)` happening in the `fail` codepath would leave dangling pointers in `s_priv->default_rt` and `s_priv->default_rt_load` (because only the local pointers would have been reset to `NULL`. It's probably the case already, but I think it would be safer to reset `rt` and `rt_load` to `NULL` after they are transfered to the private context.

But now that I think about it, you may have a similar issue with the texture, where it could actually fail (for instance during the rendertarget creation) and leave a dangling free'ed texture in `s_priv->color`.

BTW, I'm assuming you're not working with `s_priv->default_rt` and `s_priv->default_rt_load` directly because you want this code to be somehow resilient in case of error? If not then maybe it's better to work directly with those.

2022-01-04 23:27 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +    }
you could return directly `NGL_ERROR_MEMORY` here.

2022-01-04 23:27 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            .store_op   = NGLI_STORE_OP_STORE,
is it OK to set load/store op even if the depth stencil is `NULL`?

2022-01-05 08:56 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            .store_op   = NGLI_STORE_OP_STORE,
It is. With ngli_rendertarget_init() if the depth attachment is NULL, the load_op/store_op are ignored. With ngli_default_rendertarget_init() (wrapping the default framebuffer), the load_op/store_op are taken into account and works with NULL attachments.

2022-01-05 09:01 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +    }
Done.

2022-01-05 09:02 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +    }
I also removed the `goto` and `fail` label.

2022-01-05 09:32 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
> `create_rendertarget()` calls `ngli_rendertarget_freep()` in case of failure, but you do have them in this codepath as well (under the `fail:` label).

Is that an issue ? the code can fail at any point and I need to cleanup all the allocated resources (cv_texture, texture, rt, rt_load).

> 
> The code looks a bit fragile too, in particular around this:
> 
> ```c
> s_priv->default_rt = rt;
> s_priv->default_rt_load = rt_load;
> ```
> 
> If it was possible to fail after these assignments (it can't right now fortunately), then `ngli_rendertarget_freep(&rt)` and `ngli_rendertarget_freep(&rt_load)` happening in the `fail` codepath would leave dangling pointers in `s_priv->default_rt` and `s_priv->default_rt_load` (because only the local pointers would have been reset to `NULL`. It's probably the case already, but I think it would be safer to reset `rt` and `rt_load` to `NULL` after they are transfered to the private context.
> 
> But now that I think about it, you may have a similar issue with the texture, where it could actually fail (for instance during the rendertarget creation) and leave a dangling free'ed texture in `s_priv->color`.
> 
> BTW, I'm assuming you're not working with `s_priv->default_rt` and `s_priv->default_rt_load` directly because you want this code to be somehow resilient in case of error? If not then maybe it's better to work directly with those.

This is the idea. I don't want to destroy the previous rendertargets before we are sure we can use the new ones. Destroying the previous resources first would require to mark the context as "failed" if an error happens when changing the rendertargets and making the gpu context acts accordingly. Maybe it is a saner behavior after all, I'm not sure being error resilient here adds much value. If the user can't render to the desired target maybe we should stop rendering (until a new target is provided) instead of rendering to the old target. What do you think ?

2022-01-05 09:40 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
If that helps with the current code, I can remove the current `goto/label` flow, I just need to free-up all the resources in case of error while creating the two rendertargets.

2022-01-05 09:43 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
Something like
``` patch
diff --git a/libnodegl/backends/gl/gpu_ctx_gl.c b/libnodegl/backends/gl/gpu_ctx_gl.c
index 7fb72a74..f7cee804 100644
--- a/libnodegl/backends/gl/gpu_ctx_gl.c
+++ b/libnodegl/backends/gl/gpu_ctx_gl.c
@@ -528,15 +528,14 @@ static int update_capture_cvpixelbuffer(struct gpu_ctx *s, CVPixelBufferRef capt
     struct rendertarget *rt = NULL;
     struct rendertarget *rt_load = NULL;

-    int ret = 0;
     if (capture_buffer) {
-        ret = wrap_capture_cvpixelbuffer(s, capture_buffer, &texture, &cv_texture);
+        int ret = wrap_capture_cvpixelbuffer(s, capture_buffer, &texture, &cv_texture);
         if (ret < 0)
-            goto fail;
+            return ret;
     } else {
         ret = create_texture(s, NGLI_FORMAT_R8G8B8A8_UNORM, 0, &texture);
         if (ret < 0)
-            goto fail;
+            return ret;
     }

     struct texture *color         = s_priv->ms_color ? s_priv->ms_color : texture;
@@ -546,8 +545,14 @@ static int update_capture_cvpixelbuffer(struct gpu_ctx *s, CVPixelBufferRef capt
     if ((ret = create_rendertarget(s, color, resolve_color, depth_stencil,
                                    NGLI_LOAD_OP_CLEAR, &rt)) < 0 ||
         (ret = create_rendertarget(s, color, resolve_color, depth_stencil,
-                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
-        goto fail;
+                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0) {
+        ngli_rendertarget_freep(&rt);
+        ngli_rendertarget_freep(&rt_load);
+        ngli_texture_freep(&texture);
+        if (cv_texture)
+            CFRelease(cv_texture);
+        return ret;
+    }

     ngli_rendertarget_freep(&s_priv->default_rt);
     ngli_rendertarget_freep(&s_priv->default_rt_load);
@@ -561,15 +566,6 @@ static int update_capture_cvpixelbuffer(struct gpu_ctx *s, CVPixelBufferRef capt
     s_priv->capture_cvtexture = cv_texture;

     return 0;
-
-fail:
-    ngli_rendertarget_freep(&rt);
-    ngli_rendertarget_freep(&rt_load);
-    ngli_texture_freep(&texture);
-    if (cv_texture)
-        CFRelease(cv_texture);
-
-    return ret;
 }
 #endif
```

2022-01-05 11:15 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
You may be leaking `cv_texture` if create texture fails in this diff.

> > BTW, I'm assuming you're not working with `s_priv->default_rt` and `s_priv->default_rt_load` directly because you want this code to be somehow resilient in case of error? If not then maybe it's better to work directly with those.
> 
> This is the idea. I don't want to destroy the previous rendertargets before we are sure we can use the new ones. Destroying the previous resources first would require to mark the context as "failed" if an error happens when changing the rendertargets and making the gpu context acts accordingly. Maybe it is a saner behavior after all, I'm not sure being error resilient here adds much value. If the user can't render to the desired target maybe we should stop rendering (until a new target is provided) instead of rendering to the old target. What do you think ?

This logic seems specific to `update_capture_cvpixelbuffer()` (it's not done in `offscreen_rendertarget_init()` typically). I don't mind having resilience built-in but, does it actually work? What happens if the new user expectations are not actually backed by the proper data; aren't we risking overwriting or something? Isn't it going to generate garbage anyway? You're still returning an error, so right now you're making it resilient because you're expecting the user to continue the execution even in case of error.

To summarize, I'm not opposed to resilience, but it needs guarantee that it works, not because of faith in over-engineering. I understand that testing this is stuff is pretty complex, but are we able to trigger that even manually somehow? Maybe even a comment describing the exact scenario we're dealing with here would help.

2022-01-05 12:37 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
Thanks for your input. I just had a quick look at `api.c` and it makes me wonder why I'm questioning myself about what would be the correct behavior.
``` c
static int cmd_set_capture_buffer(struct ngl_ctx *s, void *capture_buffer)
{
    struct ngl_config *config = &s->config;

    int ret = ngli_gpu_ctx_set_capture_buffer(s->gpu_ctx, capture_buffer);
    if (ret < 0) {
        if (s->scene) {
            ngli_node_detach_ctx(s->scene, s);
            ngl_node_unrefp(&s->scene);
        }
        config->capture_buffer = NULL;
        return ret;
    }

    config->capture_buffer = capture_buffer;

    return 0;
}
```

So, we should not try to be error resilient in `ngli_gpu_ctx_set_capture_buffer()`. We already detach the scene if an error happens and we should also destroy the gpu context and mark the ngl context has "*not* configured" preventing later calls to the rest of the API. Do you agree ?

2022-01-05 12:45 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
Sounds reasonable. Do we have that kind of behavior (context reset on error) in other scenarios?

A bit unrelated but I don't see any logging happening in these scenarios. Maybe a top level log stating "thing got wrong because <error-string>, resetting context" would be welcome.

2022-01-05 13:55 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                   NGLI_LOAD_OP_LOAD, &rt_load)) < 0)
Added the relevant commits to simplify `update_capture_cvpixelbuffer()`.

2022-01-06 15:43 UTC, cboesch-gpsw reviewed
Despite my nitpicking I like this simplification :)

2022-01-06 15:43 UTC, cboesch-gpsw commented on libnodegl/api.c
> +    ngli_gpu_ctx_wait_idle(s->gpu_ctx);
This is gpu ctx call, so why isn't this done in the backend specific implementation of `ngli_gpu_ctx_set_capture_buffer()`? Having the user responsible for calling this sync requirement feels like exposing gpu ctx implementation specific quirks to the user.

2022-01-06 15:43 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            .clear_value[3] = config->clear_color[3],
not a blocking comment since it's already present, but I think you can do `.clear_value = {NGLI_ARG_VEC4(config->clear_color)},`

2022-01-06 15:43 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        ret = ngli_default_rendertarget_gl_init(rendertarget, &params);
Would it be even safer to have the asserts in `ngli_default_rendertarget_gl_init()` or can that function work with non-null attachments?

2022-01-10 11:11 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        ret = ngli_default_rendertarget_gl_init(rendertarget, &params);
Done in https://github.com/gopro/gopro-lib-node.gl/pull/368, so I removed the above asserts.

2022-01-10 11:30 UTC, mbouron-gpsw commented on libnodegl/api.c
> +    ngli_gpu_ctx_wait_idle(s->gpu_ctx);
Sounds good, i removed the commit entirely (no synchronization is needed on the GL side).

2022-01-10 11:44 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +    }
Nit:
```c
    int ret = color ? ngli_rendertarget_init(rendertarget, &params);
                    : ngli_default_rendertarget_gl_init(rendertarget, &params);
```
?

2022-01-10 11:46 UTC, cboesch-gpsw approved these changes

2022-01-10 15:36 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +    }
I add code later on to the else block, so it's not possible to simplify it this way.

2022-01-11 08:58 UTC, merged