pgcraft: fix buffers and textures bindings
gopro/gopro-lib-node.gl pull request #376
Opened 2022-01-30 21:02 UTC by mbouron-gpsw

2022-01-30 23:23 UTC, cboesch-gpsw requested changes
Only cosmetics, LGTM otherwise, thanks

2022-01-30 23:23 UTC, cboesch-gpsw commented on tests/data.py
> +            ngl.UniformFloat(value=0.5, label='opacity')
missing trailing comma

2022-01-30 23:23 UTC, cboesch-gpsw commented on tests/data.py
> +            ngl.UniformVec3(value=COLORS.white, label='color')
ditto

2022-01-30 23:23 UTC, cboesch-gpsw commented on tests/data.py
> +def data_vertex_and_fragment_blocks(cfg):
can you move the commit description as a docstring into this function?

2022-01-30 23:23 UTC, cboesch-gpsw commented on tests/data.py
> +        layout='std140',
Fine as is, but wouldn't it make sense to parametrize the layouts so that multiple combination are triggered? (ubo-ubo, ubo-ssbo, ssbo-ssbo). Not a blocking comment since we may end up dropping the layout anyway at some point, and since the specs seems pretty clear about it.

2022-01-30 23:23 UTC, cboesch-gpsw commented on libnodegl/pgcraft.c
> +        s->next_bindings[BIND_ID(i, NGLI_BINDING_TYPE_TEXTURE)] = &s->bindings[1];
Sounds like an important fix for the users. Can you mention that in the Changelog?

2022-01-31 08:36 UTC, mbouron-gpsw commented on tests/data.py
> +            ngl.UniformFloat(value=0.5, label='opacity')
Fixed.

2022-01-31 08:36 UTC, mbouron-gpsw commented on tests/data.py
> +            ngl.UniformVec3(value=COLORS.white, label='color')
Fixed.

2022-01-31 08:37 UTC, mbouron-gpsw commented on tests/data.py
> +def data_vertex_and_fragment_blocks(cfg):
Done (I've kept the commit description though).

2022-01-31 08:43 UTC, mbouron-gpsw commented on tests/data.py
> +        layout='std140',
It makes sense, the test could be declined into multiple tests triggering multiple scenarios. I've chosen explicitly std140 so this test can run on OpenGLES 3.0 hardware. But if that's ok with you, i'll do that later.

2022-01-31 08:46 UTC, cboesch-gpsw commented on tests/data.py
> +        layout='std140',
Sure, again not a blocker.

2022-01-31 08:49 UTC, mbouron-gpsw commented on libnodegl/pgcraft.c
> +        s->next_bindings[BIND_ID(i, NGLI_BINDING_TYPE_TEXTURE)] = &s->bindings[1];
Done.

2022-01-31 08:55 UTC, cboesch-gpsw approved these changes

2022-02-01 10:57 UTC, merged