nodegl: re-introduce wrapped OpenGL context support
gopro/gopro-lib-node.gl pull request #415
Opened 2022-03-28 13:08 UTC by mbouron-gpsw

2022-04-22 15:52 UTC, cboesch-gpsw requested changes

2022-04-22 15:52 UTC, cboesch-gpsw commented on tests/api.py
> +    assert ret != 0
can we have `assert ret != 0, "expected to fail with offscreen"`?

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/scripts/gen-gl-wrappers.py
> +    'glGetFramebufferAttachmentParameteriv',
double quotes

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/api.c
> -
I think it makes sense in this commit to explain the rationale of moving the check down into the backend themselves: it's very likely someone in the future will eventually try to factor them out up. AFAIK there are several reasons:
1. sanity checks may get customized in the future, typically the supported resolution may depend on backend capabilities known late
2. the introduction of the wrapped mode is going to be (at least temporarily) in a dedicated backend structure, and still need to be entwined within these checks, so having them at top level prevents that
3. some currently unsupported operations may become supported in some specific backends only (pick an example maybe)

Maybe more?

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glcontext_eagl.m
> +static int eagl_init_wrapped(struct glcontext *ctx, uintptr_t display, uintptr_t window, uintptr_t other)
Is the error handling reliable enough so that each glcontext implementation can have their support added progressively, that is in separate commits?

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/backends/gl/glcontext_eagl.m
> +        return -1;
Do you mind starting to use correct error code for newly added code or do you want to defer that to later™?

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/nodegl.h.in
> +    int wrapped;
sounds like `external` is a better term than "wrapped"

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/nodegl.h.in
> +    void *backend_config; /* Backend specific configuration */
maybe explicit `ngl_config_* struct`

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/nodegl.h.in
> +                      This field is ignored if the context is wrapped. */
Is it ignored or are we erroring out?

2022-04-22 15:52 UTC, cboesch-gpsw commented on CHANGELOG.md
> +- Wrapped OpenGL context support
Wrong changelog entry, thisi s already released

Also, you absolutely need to document the ABI break (the addition of `backend_config`) in the appropriate section

2022-04-22 15:52 UTC, cboesch-gpsw commented on pynodegl/_pynodegl.pyx
> +            ptr = backend_config.cptr()
can you cdef + assign on the same line in the scope? And maybe even inline on the assignment line?

2022-04-22 15:52 UTC, cboesch-gpsw commented on pynodegl/_pynodegl.pyx
> +    int ngl_gl_wrap_framebuffer(ngl_ctx *s, int framebuffer);
no trailing `;`

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/nodegl.h.in
> + * Wrap a new external OpenGL framebuffer and use it for rendering. The wrapped
You're repeating the same sentence twice

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        } const components[] = {
can you move the `const` before the struct?

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            GLint type = GL_NONE;
`GL_NONE` on a `GLint`? (Not a `GLEnum` or something?) You're comparing against `0` in the condition below.

2022-04-22 15:52 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            GLint size;
This is not initialized like `type` above

2022-04-22 15:52 UTC, cboesch-gpsw commented on qt/main6.py
> +
can you remove this commit?

2022-04-22 16:04 UTC, mbouron-gpsw commented on libnodegl/nodegl.h.in
> +                      This field is ignored if the context is wrapped. */
It is ignored.

2022-04-22 21:52 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            GLint type = GL_NONE;
`glGetFramebufferAttachmentParameteriv()` returns a `GLint` which when `GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE` is queried can either be `GL_NONE`,  `GL_FRAMEBUFFER_DEFAULT`, `GL_TEXTURE` or  `GL_RENDERBUFFER`.
`GL_NONE` is defined as `0` so IMHO there is no point in declaring type as a GLenum and casting its address to a `GLint *` and checking explicitly the result against GL_NONE.
I changed `GLint type = GL_NONE;` to `GLint type = 0;` through.

2022-04-22 21:52 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +            GLint size;
Initialized to 0.

2022-04-22 21:53 UTC, mbouron-gpsw commented on qt/main6.py
> +
It is planned, cf PR description.

2022-04-22 21:54 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glcontext_eagl.m
> +        return -1;
I prefer to defer that to later™. I'll do that in a separate PR for the whole glcontext* files at once.

2022-04-22 21:55 UTC, mbouron-gpsw commented on libnodegl/scripts/gen-gl-wrappers.py
> +    'glGetFramebufferAttachmentParameteriv',
Fixed.

2022-04-22 21:57 UTC, mbouron-gpsw commented on tests/api.py
> +    assert ret != 0
Ok but we should do that for the other asserts then.

2022-04-22 22:04 UTC, mbouron-gpsw commented on libnodegl/backends/gl/glcontext_eagl.m
> +static int eagl_init_wrapped(struct glcontext *ctx, uintptr_t display, uintptr_t window, uintptr_t other)
It's not possible, if a platform is defined it must provide both wrapped and non-wrapped classes.

2022-04-22 22:05 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        } const components[] = {
Done.

2022-04-22 22:11 UTC, mbouron-gpsw commented on libnodegl/nodegl.h.in
> +    void *backend_config; /* Backend specific configuration */
Done.

2022-04-22 23:07 UTC, cboesch-gpsw commented on tests/api.py
> +    assert ret != 0
dunno, it took me a while to figure out what was supposed to cause the failure. It's not a blocking comment.

2022-04-23 09:08 UTC, mbouron-gpsw commented on libnodegl/api.c
> -
Done.

2022-04-23 09:09 UTC, mbouron-gpsw commented on libnodegl/nodegl.h.in
> + * Wrap a new external OpenGL framebuffer and use it for rendering. The wrapped
Fixed.

2022-04-23 09:15 UTC, mbouron-gpsw commented on CHANGELOG.md
> +- Wrapped OpenGL context support
Done.

2022-04-23 09:15 UTC, mbouron-gpsw commented on pynodegl/_pynodegl.pyx
> +    int ngl_gl_wrap_framebuffer(ngl_ctx *s, int framebuffer);
Fixed.

2022-04-23 09:43 UTC, cboesch-gpsw commented on CHANGELOG.md
> +- `backend_config` field to the `ngl_config` structure (API/ABI break)
AFAICT it doesn't break the API, only the ABI

2022-04-23 09:44 UTC, cboesch-gpsw commented on libnodegl/backends/gl/api_gl.c
> +    struct ngl_config_gl *config_gl = config->backend_config;
can be const

2022-04-23 09:52 UTC, mbouron-gpsw commented on CHANGELOG.md
> +- `backend_config` field to the `ngl_config` structure (API/ABI break)
Fixed.

2022-04-23 09:52 UTC, mbouron-gpsw commented on libnodegl/backends/gl/api_gl.c
> +    struct ngl_config_gl *config_gl = config->backend_config;
Done.

2022-04-23 09:55 UTC, mbouron-gpsw commented on pynodegl/_pynodegl.pyx
> +            ptr = backend_config.cptr()
It's not possible:
```
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            config.swap_interval = kwargs.get('swap_interval', -1)
            config.offscreen = kwargs.get('offscreen', 0)
            backend_config = kwargs.get('backend_config')
            cdef uintptr_t ptr
            if backend_config is not None:
                cdef uintptr_t ptr = backend_config.cptr()
                    ^
    ------------------------------------------------------------

    _pynodegl.pyx:554:17: cdef statement not allowed here
```
This is why i used this form.

2022-04-23 13:59 UTC, cboesch-gpsw approved these changes

2022-04-23 22:12 UTC, merged