ci_android: specify version of sxplayer to download
gopro/gopro-lib-node.gl pull request #431
Opened 2022-04-15 15:58 UTC by mrobertseidowsky-gpsw

2022-04-15 16:00 UTC, cboesch-gpsw requested changes
`ci/android` in the commit message.

LGTM otherwise

2022-04-15 16:00 UTC, cboesch-gpsw commented on .github/workflows/ci_android.yml
> +        sxplayer_version: [9.12.0]
Not a blocking comment but I'm not sure why we use a matrix here

2022-04-15 16:06 UTC, mrobertseidowsky-gpsw commented on .github/workflows/ci_android.yml
> +        sxplayer_version: [9.12.0]
I thought it can be relevant to be able to test several version but let me know if you prefer a simple global variable.

2022-04-15 16:07 UTC, mrobertseidowsky-gpsw commented
> `ci/android` in the commit message.
> 
> LGTM otherwise

done.

2022-04-18 11:13 UTC, cboesch-gpsw approved these changes

2022-04-18 12:39 UTC, mbouron-gpsw approved these changes

2022-04-19 07:32 UTC, merged