gpu_ctx_vk: initialize the memory returned by ngli_darray_push() wher…
gopro/gopro-lib-node.gl pull request #440
Opened 2022-04-21 16:00 UTC by mbouron-gpsw

…e relevant

We need to ensure that the memory contained by the different arrays
populated in create_render_resources() is properly initialized.

This commit fixes potential crashes happening in
destroy_render_resources() due to uninitialized memory left by
create_render_resources() if an error happened.

2022-04-21 16:05 UTC, cboesch-gpsw approved these changes

2022-04-21 21:52 UTC, cboesch-gpsw requested changes
How about `depth_stencil` in the surrounding scope?

2022-04-28 08:27 UTC, cboesch-gpsw requested changes

2022-04-28 08:27 UTC, cboesch-gpsw commented on libnodegl/backends/vk/gpu_ctx_vk.c
> +        struct rendertarget *rt;
`rt = NULL` for consistency?

2022-04-28 08:27 UTC, cboesch-gpsw commented on libnodegl/backends/vk/gpu_ctx_vk.c
> +        struct rendertarget *rt_load;
ditto, `rt_load = NULL`

2022-04-28 08:28 UTC, mbouron-gpsw commented on libnodegl/backends/vk/gpu_ctx_vk.c
> +        struct rendertarget *rt_load;
Done.

2022-04-28 08:29 UTC, mbouron-gpsw commented on libnodegl/backends/vk/gpu_ctx_vk.c
> +        struct rendertarget *rt;
Done.

2022-04-28 08:29 UTC, cboesch-gpsw approved these changes

2022-04-28 08:46 UTC, merged