API split
gopro/gopro-lib-node.gl pull request #441
Opened 2022-04-21 19:53 UTC by mbouron-gpsw

2022-04-21 21:50 UTC, cboesch-gpsw requested changes
Nice.

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/gl/api_gl.c
> +#include "config.h"
missing copyright header

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/gl/api_gl.c
> +#include "backends/gl/gpu_ctx_gl.h"
This one is not needed anymore in `api.c`

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/vk/api_vk.c
> +#include "internal.h"
missing copyright header

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/gl/api_gl.c
> +    ngli_gpu_ctx_wait_idle(s->gpu_ctx);
vk doesn't need this one?

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/gl/api_gl.c
> +    struct resize_params params = {
Do you mind marking it const and casting the dispatch call? The struct is actually const, only the transmission layer needs the cast hack.

Edit: OK just realized it preserves the current code, so feel free to ignore or change it in a separate commit.

2022-04-21 21:50 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.h
> +int ngli_gpu_ctx_gl_release_current(struct gpu_ctx *s);
Are you going to add other functions like this by removing some very GL oriented callbacks in `struct gpu_ctx_class` at some point?

2022-04-22 05:50 UTC, mbouron-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.h
> +int ngli_gpu_ctx_gl_release_current(struct gpu_ctx *s);
Yes, typically `ngli_gpu_ctx_gl_reset_state(struct gpu_ctx *s);` that will come with the upcoming PR adding support for external OpenGL contexts.

2022-04-22 05:56 UTC, mbouron-gpsw commented on libnodegl/backends/gl/api_gl.c
> +#include "config.h"
Done.

2022-04-22 05:56 UTC, mbouron-gpsw commented on libnodegl/backends/gl/api_gl.c
> +#include "backends/gl/gpu_ctx_gl.h"
Done.

2022-04-22 05:56 UTC, mbouron-gpsw commented on libnodegl/backends/vk/api_vk.c
> +#include "internal.h"
Done.

2022-04-22 06:01 UTC, mbouron-gpsw commented on libnodegl/backends/gl/api_gl.c
> +    ngli_gpu_ctx_wait_idle(s->gpu_ctx);
Indeed it does, I moved `ngli_gpu_ctx_wait_idle(s->gpu_ctx);` to `ngli_ctx_set_scene()` in a separate commit.

2022-04-22 07:17 UTC, cboesch-gpsw approved these changes

2022-04-22 07:55 UTC, merged