hwmap: add Mediacodec/Vulkan support
gopro/gopro-lib-node.gl pull request #460
Opened 2022-05-08 08:52 UTC by mbouron-gpsw

2022-05-09 12:11 UTC, cboesch-gpsw requested changes

2022-05-09 12:11 UTC, cboesch-gpsw commented on libnodegl/backends/vk/pipeline_vk.c
> +                texture_binding->ycbcr_sampler = ngli_ycbcr_sampler_vk_ref(texture_vk->ycbcr_sampler);
I think you need to explain somewhere the purpose of the ref counting and the related lifetime considerations.

2022-05-09 12:11 UTC, cboesch-gpsw commented on libnodegl/backends/vk/ycbcr_sampler_vk.c
> +        LOG(ERROR, "could not create sampler ycbcr conversion: %s", ngli_vk_res2str(res));
nit: YCbCr

2022-05-09 12:11 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +        'src': files('backends/vk/hwmap_mediacodec_vk.c'),
Add a changelog entry maybe?

2022-05-09 12:13 UTC, mbouron-gpsw commented on libnodegl/backends/vk/vkcontext.c
> +        VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME,
We require VK_API_VERSION_1_1.

2022-05-09 12:15 UTC, mbouron-gpsw commented on libnodegl/backends/vk/texture_vk.c
> +    s_priv->wrapped_image = 1;
Fixed.

2022-05-09 12:17 UTC, mbouron-gpsw commented on libnodegl/backends/vk/pipeline_vk.c
> +static int need_desc_set_layout_update(struct pipeline *s,
Removed.

2022-05-09 12:17 UTC, mbouron-gpsw commented on libnodegl/android_ctx.c
> +        const char *required_extensions[] = {
Done.

2022-05-09 12:38 UTC, mbouron-gpsw commented on libnodegl/android_ctx.c
> +        }
Done.

2022-05-09 12:39 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +    int32_t mem_type_index = ngli_vkcontext_find_memory_type(vk, mem_reqs.memoryTypeBits, mem_props);
Done.

2022-05-09 12:44 UTC, mbouron-gpsw commented on libnodegl/backends/vk/ycbcr_sampler_vk.c
> +    return (p0->android_external_format == p1->android_external_format &&
Removed.

2022-05-09 12:44 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +#include <android/hardware_buffer_jni.h>
Removed.

2022-05-09 12:45 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +    memcpy(matrix, crop_matrix, sizeof(crop_matrix));
It is planned in a later PR.

2022-05-09 12:46 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +        LOG(WARNING, "ycbcr conversions must have same min/mag filters: "
Fixed.

2022-05-09 12:47 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +        .extent.depth  = 1,
Done.

2022-05-09 12:49 UTC, mbouron-gpsw commented on libnodegl/meson.build
> +        'src': files('backends/vk/hwmap_mediacodec_vk.c'),
Done.

2022-05-09 12:52 UTC, mbouron-gpsw commented on libnodegl/backends/vk/ycbcr_sampler_vk.c
> +        LOG(ERROR, "could not create sampler ycbcr conversion: %s", ngli_vk_res2str(res));
Fixed.

2022-05-09 18:52 UTC, mbouron-gpsw commented on libnodegl/backends/vk/hwmap_mediacodec_vk.c
> +    memcpy(matrix, crop_matrix, sizeof(crop_matrix));
Well, it's done in this PR.

2022-05-09 22:36 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +        'src': files('backends/vk/hwmap_mediacodec_vk.c'),
You've added it to the wrong release

2022-05-10 06:10 UTC, mbouron-gpsw commented on libnodegl/meson.build
> +        'src': files('backends/vk/hwmap_mediacodec_vk.c'),
Sorry, fixed.

2022-05-10 15:02 UTC, cboesch-gpsw approved these changes

2022-05-12 10:33 UTC, merged