Texture misc
gopro/gopro-lib-node.gl pull request #475
Opened 2022-05-18 14:46 UTC by mbouron-gpsw

2022-05-19 20:11 UTC, cboesch-gpsw requested changes
I like this PR

2022-05-19 20:11 UTC, cboesch-gpsw commented on libnodegl/backends/gl/hwmap_vaapi_gl.c
> +    ngli_glGenTextures(gl, 1, vaapi->gl_planes);
shouldn't this be 2 planes?

2022-05-19 20:11 UTC, cboesch-gpsw commented on libnodegl/backends/gl/hwmap_videotoolbox_darwin_gl.c
> +    ngli_glBindTexture(gl, plane_gl->target, 0);
Why abstract it here but not in `vt_darwin_init()`?

2022-05-19 21:07 UTC, mbouron-gpsw commented on libnodegl/backends/gl/hwmap_vaapi_gl.c
> +    ngli_glGenTextures(gl, 1, vaapi->gl_planes);
Good catch, it is fixed. For the record, playing back a single media was working fine, the special texture handle 0 was used for the chroma plane without any issue :')

2022-05-19 21:10 UTC, mbouron-gpsw commented on libnodegl/backends/gl/hwmap_videotoolbox_darwin_gl.c
> +    ngli_glBindTexture(gl, plane_gl->target, 0);
I changed the commit and went the other way around (ie: using GL_TEXTURE_RECTANGLE where relevant).

2022-05-20 07:39 UTC, cboesch-gpsw commented on libnodegl/backends/gl/hwmap_vaapi_gl.c
> +    ngli_glGenTextures(gl, 1, vaapi->gl_planes);
Hopefully https://github.com/gopro/gopro-lib-node.gl/pull/479 will help here

2022-05-20 07:52 UTC, cboesch-gpsw approved these changes

2022-05-20 11:30 UTC, merged