build: handle OpenGLES as a separate backend build-wise
gopro/gopro-lib-node.gl pull request #483
Opened 2022-05-24 11:37 UTC by mbouron-gpsw

Some platforms only support OpenGL or OpenGLES (for example, macOS only
supports OpenGL).

This prevents our probing mechanism from trying to create an OpenGLES
context with NSGL and outputting the following error message:

    nsgl_init: unsupported backend: 2, only OpenGL is supported by NSGL

2022-05-24 12:33 UTC, cboesch-gpsw requested changes

2022-05-24 12:33 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +    if (gbackend_name == 'gl' or gbackend_name == 'gles') and vaapi_enabled
`gbackend_name in ['gl', 'gles']`

2022-05-24 12:33 UTC, cboesch-gpsw commented on configure.py
> +        choices=("gl", "gles", "vk", "mem", "scene", "gpu_capture"),
`libnodegl/meson_options.txt` doesn't have a `gles` option for `--debug-opts`, and I think that's fine: there is currently no way to have a build where gl and gles backends have a different debug system (this would imply the addition of runtime checks for `check_error_code` / `ngli_glcontext_check_gl_error`. I think you should leave this out and keep a `DEBUG_GL` shared for both until then.

2022-05-25 10:37 UTC, mbouron-gpsw commented on libnodegl/meson.build
> +    if (gbackend_name == 'gl' or gbackend_name == 'gles') and vaapi_enabled
Done.

2022-05-25 10:41 UTC, mbouron-gpsw commented on configure.py
> +        choices=("gl", "gles", "vk", "mem", "scene", "gpu_capture"),
Removed.

2022-05-25 10:49 UTC, cboesch-gpsw approved these changes
LGTM thanks

You may want to add some ifdefery in `gpu_ctx_gl.c` to prevent the systematic declarations of both `ngli_gpu_ctx_{gl,gles}`

2022-05-25 14:57 UTC, cboesch-gpsw approved these changes

2022-05-25 15:11 UTC, merged