GPU capture support for macOS
gopro/gopro-lib-node.gl pull request #508
Opened 2023-02-14 21:05 UTC by steventang-gpsw

This PR added OpenGL GPU capture for macOS.

2023-02-14 23:11 UTC, kgrant-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.h
> +#if  defined(TARGET_DARWIN)
```suggestion
#if defined(TARGET_DARWIN)
```

2023-02-14 23:16 UTC, kgrant-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        CFRelease(cv_texture);
It looks like `CFRelease` is equivalent to `CVBufferRelease` except that the latter will implicitly check for `NULL` (`CFRelease` crashes if the texture is still `NULL`).

It is probably safe to assume that `CVOpenGLTextureCacheCreateTextureFromImage` will provide a non-`NULL` texture though, since the error is checked above.

2023-02-14 23:21 UTC, kgrant-gpsw commented on libnodegl/backends/gl/glcontext_nsgl.m
> +                                                &nsgl->texture_cache);
Do we need a unique cache, or can `ngli_glcontext_get_texture_cache` be used?

2023-02-14 23:23 UTC, kgrant-gpsw commented on libnodegl/backends/gl/glcontext_nsgl.m
>      if (nsgl->framework)
What is the difference between these two `uninit` cases (and how do we know that the cache must be freed in both)?

2023-02-14 23:24 UTC, kgrant-gpsw reviewed
I think the changes mostly look fine, just wondering about the extra cache.
Also it seems a linter check failed, maybe it does not like formatting somewhere.

2023-02-15 10:07 UTC, cboesch-gpsw requested changes
1. It looks like your PR includes several changes; in particular there is a mix between the NSGL and the backend itself. Can't those be split?
2. Why do you mention "GPU capture"?
3. Your branch name doesn't follow the convention `<name>/<short-desc>` and is also leaking internal information about the GoPro company into a public repository

2023-02-15 10:07 UTC, cboesch-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +                                                                   &cv_texture);
vertical indent is off

2023-02-15 15:12 UTC, steventang-gpsw commented on VERSION
> +2023.2
Sorry, didn't know the rules, will look into it and do some modifications
1. About the version number, I'll revert it back
2. About your question 1, if it is mandatory to split, I'll split, otherwise, it is better to keep it as one since partial might be blocked by test.
3. About question 2, is "Support OS X Core Video capture with OpenGL" better? or your suggestions
4. That branch name was generated by the JIRA ticket, any suggested branch name?

2023-02-15 15:14 UTC, steventang-gpsw commented
> I think the changes mostly look fine, just wondering about the extra cache. Also it seems a linter check failed, maybe it does not like formatting somewhere.

Will fix the format, BTW, do we have any rules which we can apply to clang-format for automatic formatting?

2023-02-15 15:41 UTC, steventang-gpsw commented on libnodegl/backends/gl/glcontext_nsgl.m
>      if (nsgl->framework)
when calling OpenGL context creation, we can ask the backend to create either external OpenGL context or Internal OpenGL context, the definition of external is 
```
struct ngl_config_gl {
    /*
     * Whether the OpenGL context is external or not. If the OpenGL context is
     * external, it is the user responsibility to manage the OpenGL context and
     * make sure it is current before calling any of the ngl_* functions.
     */
    int external;
    /*
     * External OpenGL framebuffer used for rendering. The framebuffer must
     * have a color attachment composed of 4 color components (R, G, B, A) and
     * a combined depth and stencil buffer attached to it.
     */
    uint32_t external_framebuffer;
};
```
One of two deinitialization  (nsgl_uninit and nsgl_uninit_external) will be called when doing clean up

2023-02-15 15:51 UTC, steventang-gpsw commented on libnodegl/backends/gl/glcontext_nsgl.m
> +                                                &nsgl->texture_cache);
The texture cache was created here [OpenGL context initialization] only once, later, we use ngli_glcontext_get_texture_cache to get the reference of this one for using until it was destroyed.

2023-02-15 15:55 UTC, steventang-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.c
> +        CFRelease(cv_texture);
Will update to use CVOpenGLTextureRelease, this function is equivalent to CFRelease, but is NULL safe.

2023-02-15 15:56 UTC, steventang-gpsw commented on libnodegl/backends/gl/gpu_ctx_gl.h
> +#if  defined(TARGET_DARWIN)
Adopted

2023-02-15 16:36 UTC, closed without merging

2023-02-15 16:36 UTC, steventang-gpsw commented
Close this one, use PR # 513 instead.