utils: Add properties informations with a rc file for the dll under windows
gopro/gopro-lib-node.gl pull request #516
Opened 2023-02-20 13:30 UTC by rlavarec-gpsw

Add informations inside the dll
- Copyrights
- Version
- Platform
- Name

2023-02-20 16:37 UTC, cboesch-gpsw requested changes
1. Commit prefix should be "build", not "utils"
2. You updated the PR description but not the commit message
3. Can you explain in the commit description what this is useful for?
4. I think the `rc` directory is unnecessary, unless you plan to add more files like this?

2023-02-20 16:37 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +nodegl_version_cdata.set('NODEGL_PLATFORM_VERSION', fs.read('../VERSION'))
Is this mandatory? I really don't like having a dependency on the parent project.

2023-02-20 16:37 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +nodegl_version_cdata.set('NODEGL_COPYRIGHT', 'Copyright 2020-2023 GoPro Inc.')
I feel like we're going to forget updating the date, you may want to remove them

2023-02-20 16:37 UTC, cboesch-gpsw commented on libnodegl/rc/nodegl.rc.in
> +      BLOCK "040904B0"
How was this file generated? What is this `040904B0` magic?

2023-02-20 16:37 UTC, cboesch-gpsw commented on libnodegl/rc/nodegl.rc.in
> +	VALUE "InternalName", "@NODEGL_PLATFORM_VERSION@"
InternalName → VERSION? 🤔

2023-02-20 16:37 UTC, cboesch-gpsw commented on libnodegl/rc/nodegl.rc.in
> +      VALUE "Translation", 0x409, 1200
what is the meaning of `0x409` and `1200`?

2023-02-20 16:37 UTC, cboesch-gpsw commented on CHANGELOG.md
> +- [Windows] Add dll information (Copyrights, Version, Platform, Name)
We don't use `[tags]`, can you just write "Windows DLL information [...]"?

Also, it belongs in a "Added" subsection, not "Fixed"

2023-02-21 09:57 UTC, rlavarec-gpsw commented on libnodegl/meson.build
> +nodegl_version_cdata.set('NODEGL_PLATFORM_VERSION', fs.read('../VERSION'))
Not mandatory, but it help to know it was originated from a certain platform release.
If the VERSION file doesn't exist anymore, we will get a python error.

2023-02-21 13:10 UTC, rlavarec-gpsw commented on libnodegl/rc/nodegl.rc.in
> +	VALUE "InternalName", "@NODEGL_PLATFORM_VERSION@"
Oui je vais changer, je vais mettre la même chose que OriginalFilename

2023-02-21 13:11 UTC, rlavarec-gpsw commented on libnodegl/rc/nodegl.rc.in
> +      VALUE "Translation", 0x409, 1200
English language (0x409) in the Unicode (1200)

2023-02-21 13:12 UTC, rlavarec-gpsw commented on CHANGELOG.md
> +- [Windows] Add dll information (Copyrights, Version, Platform, Name)
Ok

2023-02-22 13:55 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +# Add properties informations with a rc file for the dll under windows
information, DLL, Windows

2023-02-22 13:55 UTC, cboesch-gpsw commented on libnodegl/meson.build
> +fs = import('fs')
trailing whitespace

2023-02-22 15:59 UTC, cboesch-gpsw commented on libnodegl/rc/nodegl.rc.in
> +      BLOCK "040904B0"
For record it's probably 040904B0 -> 0x409 (english) 0x04b0 (unicode, =1200), according to your comment below

2023-02-22 16:01 UTC, cboesch-gpsw approved these changes

2023-02-22 16:57 UTC, merged