Added macOS CoreVideo support. this PR allows macOS to turn pixelbuff…
gopro/gopro-lib-node.gl pull request #520
Opened 2023-02-27 15:08 UTC by steventang-gpsw

…er into OpenGL Rectangle texture, when doing exporting, OpenGL render the target video frames directly to the pixel buffer surface, and the encoder grab from there directly for high performance.

2023-02-27 18:43 UTC, kgrant-gpsw commented on CHANGELOG.md
> +  grab from there directly for high performance.
Should this (for now) go into the `[Unreleased]` section above?

2023-02-27 18:47 UTC, kgrant-gpsw reviewed
Looks good to me.

2023-03-02 18:04 UTC, steventang-gpsw commented
As discussed with Clément , I split the previous commit into 4 atomic commits.

2023-03-07 16:28 UTC, wmacdonald-gpsw approved these changes
Looks good to me now as well.

2023-03-09 10:41 UTC, cboesch-gpsw requested changes
1. Please add commit prefixes (look at the git history for examples)
2. Be consistent with "Added" vs "Add"
3. Please add a commit description explaining the what & why
4. How can I test this?

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +#define SAFE_CFRELEASE(p) { if ( (p) ) { CFRelease(p); (p) = NULL; } }
please use a `do { ... } while (0)` form. Actually, you have `NGLI_CFRELEASE()` doing exactly that in `src/backends/gl/hwmap_videotoolbox_ios_gl.c`. Since it's not exposed yet you can duplicate it for now, or maybe expose it in `src/utils.h` if you want do do things well (not mandatory for approval, just… better).

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    }
The condition is not needed

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +
unnecessary line break

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    SAFE_CFRELEASE(cv_texture);
Why are you releasing the `cv_texture`? There is a `*cv_texturep = cv_texture` below

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +    CVOpenGLTextureRef capture_cvtexture;
broken indent

2023-03-09 10:41 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/glcontext.c
> +}
When is this used? I don't see anything in the PR using it, did I miss it?

2023-03-09 15:57 UTC, steventang-gpsw commented
Thanks to @cboesch-gpsw for the comments, will work on the comments after I get the export pause/resume (YADA-4987) fixed, I found the cause and working on the solution for that.

2023-03-09 21:42 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +#define SAFE_CFRELEASE(p) { if ( (p) ) { CFRelease(p); (p) = NULL; } }
I was planning to move it to src/utils.h, didn't figure out how to restrict it with Apple platform, so I just copy it.

2023-03-09 23:31 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/glcontext.c
> +}
Was using it for GL_TEXTURE_RECTANGLE to GL_TEXTURE_2D conversion, but it is not necessary now, I'll remove this.

2023-03-10 15:36 UTC, steventang-gpsw commented
Sorry to @cboesch-gpsw  and @wmacdonald-gpsw , I was using git rebase command lines to fix that, and somehow I got it messed up, will revert all of those and rebase commits (+ sdk_av_engine iOS testing) Monday.

2023-03-13 21:15 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    SAFE_CFRELEASE(cv_texture);
we just assign null to the cv_texturep.

2023-03-14 01:34 UTC, steventang-gpsw commented
Tried to revert all old commits and re-commit, it didn't work, use
https://github.com/gopro/gopro-lib-node.gl/pull/523
instead, I'll close this one.

2023-03-14 01:34 UTC, closed without merging