Add Support For Layered Image Resources
gopro/gopro-lib-node.gl pull request #522
Opened 2023-03-03 04:52 UTC by wmacdonald-gpsw

Support for treating layered resources (cube maps, 3d textures, and texture arrays) as 2D image arrays when they are bound as images. This is used for compute shaders, where the use of imageLoad() and especially imageStore() is critical.

2023-03-03 15:50 UTC, hsong-gpsw approved these changes

2023-03-06 18:50 UTC, wmacdonald-gpsw commented
@cboesch-gpsw in addition to code feedback, please advise on preferences for breaking up the commit. Is one commit ok since it is all related to one feature add? Should I separate cube texture feature from 3D texture feature? Should I separate changes by each file, or by sections (add core enums, add pgcraft support, add gl support, add vk support, etc.) Should adding tests be a separate commit?

2023-03-08 09:10 UTC, cboesch-gpsw requested changes
Please use a prefix in the commit message to be a bit more specific, something like: `compute,render: support layered image texture formats`?

BTW, I'm assuming this also works with a `Render` pipeline, not just `Compute`?

With regards to your concern about code split, as is is probably fine. When the tests are large we tend to split them out but that's OK here IMO.

2023-03-08 09:10 UTC, cboesch-gpsw commented on tests/compute.py
> +@scene(show_dbg_points=scene.Bool())
You have to choose between the debug points and the fingerprint signature. In this case I believe you actually want the cue points (6 points spread on each colored area). The fingerprint kinda works but here the cue points would be more reliable I believe.

Try in ngl-control to check the `show_dbg_points` option (bottom-left of the UI) to see where the points are actually tested. You have to position them appropriately (and reduce their count). You can either hardcode the 6 positions, or use a function to generate them (below you used the histogram function to get them, you don't want that)

2023-03-08 16:12 UTC, wmacdonald-gpsw commented on tests/compute.py
> +@scene(show_dbg_points=scene.Bool())
I was wondering about this, thank you for the clarification.

2023-03-09 15:03 UTC, cboesch-gpsw commented on tests/compute.py
> +    c = lambda i,f: (i / f + (1 / (2 * f))) * 2.0 - 1.0
Nitpick, not blocking: you don't need to explicit floats (`2.0` → `2`)

2023-03-09 15:03 UTC, cboesch-gpsw commented
> @cboesch-gpsw I have made all the updates except for adding additional tests for layered images in render pipelines. Please review again, and let me know your thoughts on adding those tests.

I'm fine without these tests if you're sure you're not breaking anything

2023-03-09 17:17 UTC, wmacdonald-gpsw commented
I have addressed the linter issue and also your other feedback.

2023-03-10 09:40 UTC, cboesch-gpsw approved these changes

2023-03-10 19:25 UTC, merged