steventang/nodegl macos corevideo
gopro/gopro-lib-node.gl pull request #523
Opened 2023-03-14 01:33 UTC by steventang-gpsw

This PR allows macOS to turn pixel-buffer into OpenGL Rectangle texture, when doing exporting, OpenGL renders the target video frames directly to the pixel buffer surface, and the encoder grabs from there directly for high performance.

2023-03-14 01:51 UTC, kgrant-gpsw approved these changes

2023-03-15 08:44 UTC, cboesch-gpsw requested changes
Please do not re-open PRs it's a nightmare to have a followup on previous comments. Just re-use the PR by push-forcing into your current working branch.

2023-03-15 08:44 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +} while (0);
no `;` at the end of a `do { ... } while (0)` macro

2023-03-15 08:44 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/glcontext_nsgl.m
> +
seems you're adding trailing whitespaces here

2023-03-15 08:44 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +    CVOpenGLTextureRef capture_cvtexture;
You didn't address the comment I made originally here

2023-03-15 08:44 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
Is it really OK to bind a texture you just released?

2023-03-16 17:38 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +    CVOpenGLTextureRef capture_cvtexture;
oh, it was a tab and I didn't notice, replaced it with 4 spaces

2023-03-16 17:43 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
Yes, I didn't many video exporting tests from 720P to 5.3K video, all of them are smooth, memory usage were reasonable and no crash happened.

2023-03-16 17:51 UTC, steventang-gpsw commented
I was using fixup, but it only merged the update to the previous one, hope it will be ok

2023-03-21 00:26 UTC, wmacdonald-gpsw approved these changes

2023-03-21 12:49 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
What I'm afraid of is that it's going to read released GPU memory; so you may end up reading the wrong data, typically with a pipeline with multiple video texture bound, or eventually multiple pipelines. But maybe I'm misunderstanding something.

2023-03-21 12:50 UTC, cboesch-gpsw commented
> I was using fixup, but it only merged the update to the previous one, hope it will be ok

No it's not; please adjust the commit themselves

2023-03-21 15:56 UTC, wmacdonald-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
Looking at it closer, I also share this concern. VRAM is generally implemented using scheduled garbage collection, so actual crashes when binding a just-released resource would be rare, but there is risk of invalid data in some cases. If it were actually invalid to release this, I would expect it to be flagged in debug builds, or at least under the GPU instruments. I do wonder if it is made safe by the capture on the CoreVideo side still holding a handle internally. I'll take a closer look at this flow and see if I can understand it enough to offer some help.

2023-03-23 18:17 UTC, nsilvy-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +static int wrap_capture_cvpixelbuffer(struct gpu_ctx *s,
I wonder if defining only one function and using platform specific code each time something differs between iOS and macOS would not be easier to maintain? In order to have as much common code as possible.
```c
#if defined(TARGET_IPHONE)
CVOpenGLESTextureCacheCreateTextureFromImage();
#else
CVOpenGLTextureCacheCreateTextureFromImage();
#endif
```

2023-03-23 18:22 UTC, nsilvy-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    ngli_texture_freep(&s_priv->color);
How is this related to this commit?

2023-03-23 18:37 UTC, nsilvy-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
A couple of remarks on the commit message:
1. You could explain why you need to introduce this macro
2. `CFRelease` is actually part of `Core Foundation` and not `Core Video` like you mentioned in the title

Together with my other remarks, and looking at the commit history, I would rename the commit to something like:
```
gl/gpu_ctx_gl: add NGLI_SAFE_CFRELEASE macro

A safe-release mechanism is needed when releasing Core Foundation
objects because we don't want dangling pointers... blablabla
```

I'm not sure about which commit prefix to use though.

FYI: https://github.com/gopro/gopro-lib-node.gl/blob/main/doc/dev/ref/developers.md#integration

2023-03-23 21:35 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
I updated and did a test, looks like the memory seems to be normal, I'll keep the new updated for safety.
![image](https://user-images.githubusercontent.com/117775289/227369139-43c84632-56b0-477c-b3ac-8a0489bce78c.png)

2023-03-23 22:04 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
NGLI_CFRELEASE is using in iOS, keep it consistent, @cboesch-gpsw what do you think?

2023-03-23 23:12 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +static int wrap_capture_cvpixelbuffer(struct gpu_ctx *s,
I have a different opinion, common code is difficult to maintain, when you update the common code, you need to build both iOS and macOS to check if both are working, yes, as much common code as possible will save space, but these days the space is not a problem for the code,  the problem is people need spend double time to verify common code, and more #if #else will cause code very difficult to read.

2023-03-24 09:06 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
GPU memory leaks will not be observed with a traditional memory profiler.

2023-03-24 09:53 UTC, nsilvy-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
Oh, I didn't know the macro already existed on iOS. So why creating a new one for macOS?

2023-03-24 12:49 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.h
> +#define NGLI_CFRELEASE(ref) do { \
The macro is fine; it will allow us to share it in a common utils without additional ifdefery + lib detection within the build system

2023-03-24 14:12 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    ngli_texture_freep(&s_priv->color);
Updated in the new edited commits

2023-03-24 14:17 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/glcontext_nsgl.m
> +
seems not afaict

2023-03-24 14:24 UTC, cboesch-gpsw requested changes

2023-03-24 14:24 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/texture_gl.c
> +        s_priv->target = GL_TEXTURE_RECTANGLE;
I don't think you can have this commit before the one handling that particular target. Why did you split out this? It felt more meaningful before. Or did I miss something?

2023-03-24 14:24 UTC, cboesch-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +        NGLI_CFRELEASE(cv_texture);
Isn't this related to another commit? Didn't you squashed back some changes together?

2023-03-24 15:18 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +        NGLI_CFRELEASE(cv_texture);
The last commit is a bit big, I'll revise it.

2023-03-24 21:53 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +    NGLI_CFRELEASE(cv_texture);
agree, code revised.

2023-04-03 19:02 UTC, wmacdonald-gpsw commented on libnodegl/src/backends/gl/glcontext_nsgl.m
> +
I found two trailing whitespaces remaining on lines 121 and 122.

2023-04-03 19:07 UTC, wmacdonald-gpsw commented on libnodegl/src/backends/gl/gpu_ctx_gl.c
> +static int wrap_capture_cvpixelbuffer(struct gpu_ctx *s,
@steventang-gpsw I'm not entirely sure I agree with that, but my counterargument probably depends on some standardization and testing support that I can't guarantee we have nailed down. I have no issue with the current way you have this. It is likely to get cleaned up in an audit if we make improvements to how portability is handled.

2023-04-03 19:18 UTC, steventang-gpsw commented on libnodegl/src/backends/gl/glcontext_nsgl.m
> +
Fixed, thanks

2023-04-03 19:23 UTC, merged