Metal backend for node.gl
gopro/gopro-lib-node.gl pull request #549
Opened 2023-08-08 00:43 UTC by hsong-gpsw

Metal backend for node.gl.  There are changes in other packages:  gopro-utils-sx-bundle, ngl-ios and sdk-quik-av-engine.  I will submit them separately.

2023-08-09 18:57 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        w = width; h = height;
stylewise: separate lines?

2023-08-09 18:57 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/compute_pipeline_mtl.h
> +    int max_threads_per_group;
Could add init values

2023-08-09 18:57 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    bool enable_depth_stencil = true;
This is always true

2023-08-09 18:57 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    bool enable_depth_stencil = true;
unused

2023-08-09 18:57 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/surface_mtl.cpp
> +SurfaceMTL::SurfaceMTL(gpu_ctx *ctx, uint32_t w, uint32_t h, bool enable_depth_stencil,
`enable_depth_stencil` is unused

2023-08-09 21:40 UTC, hsong-gpsw commented on libnodegl/src/api.c
> +# define DEFAULT_BACKEND NGL_BACKEND_METAL
OK, Thanks @jstys-gpsw

2023-08-09 21:42 UTC, hsong-gpsw commented on ngl-tools/wsi_cocoa.m
> +        } /*else if (config->backend == NGL_BACKEND_METAL) {
OK

2023-08-09 21:43 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/buffer_mtl.cpp
> +{
Yes, it needs, it is part of frontend API

2023-08-09 21:47 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/compute_pipeline_mtl.h
> +    int max_threads_per_group;
Hmm, these two values are obtained at runtime when pipeline is created.

2023-08-09 21:51 UTC, wmacdonald-gpsw commented on libnodegl/meson.build
> +  if is_native == false
Yes, a little explanation here would be useful. Especially:

- We need to double check architecture handling for mac. Cross-compiling from mac to mac is now supported (x86 compiling ARM, and vice versa) in order support universal binary assembly from a single build machine.
- What does it mean that objcpp is not native on aarch64?

2023-08-09 21:55 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/compute_pipeline_mtl.h
> +    int max_threads_per_group;
Right, I just figured they should have some initial invalid value since they could be accessed prior to `create()` being called

2023-08-09 21:58 UTC, jstys-gpsw commented on libnodegl/src/backends/metal/buffer_mtl.cpp
> +{
I meant whether the function body should do anything, because it currently did not. Looking at map that's just returning a pointer to a field, so perhaps this unmap is a noop after all

2023-08-09 22:00 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        w = width; h = height;
OK, changed

2023-08-09 22:01 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/buffer_mtl.cpp
> +{
unmap() is no-op for opengl/es and metal

2023-08-09 22:06 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/compute_pipeline_mtl.h
> +    int max_threads_per_group;
OK,  I will initialize them as 0

2023-08-09 22:07 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    bool enable_depth_stencil = true;
Great catch, I will remove them.

2023-08-09 22:08 UTC, wmacdonald-gpsw commented on libnodegl/src/api.c
> +# define DEFAULT_BACKEND NGL_BACKEND_METAL
Yes GL will remain default for now. Please change it back. The steps we plan to take are:

- GL will remain default for now.
- Offer the app an API to select the backend at startup
- App will evaluate the backends to ensure they produce matching results
- App will notify us when the decision is made to change the default

2023-08-09 22:08 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    bool enable_depth_stencil = true;
Yes, I will remove them.

2023-08-09 22:08 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/surface_mtl.cpp
> +SurfaceMTL::SurfaceMTL(gpu_ctx *ctx, uint32_t w, uint32_t h, bool enable_depth_stencil,
I will remove them.

2023-08-09 22:15 UTC, wmacdonald-gpsw commented on libnodegl/src/backends/metal/Metal.hpp
Is it ok to re-publish this file? Is there no standard place it can be pulled from?

2023-08-09 22:21 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/Metal.hpp
According to this https://developer.apple.com/metal/cpp/,  It is OK to publish, and can be placed anywhere in the search path

2023-08-09 22:39 UTC, wmacdonald-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        w = width; h = height;
yes, try to avoid multi-statement lines

2023-08-09 23:17 UTC, wmacdonald-gpsw requested changes
Agree with most of Jacks notes. At minimum, we need to leave OpenGL as the default for now.

2023-08-10 01:41 UTC, hsong-gpsw commented on libnodegl/src/api.c
> +# define DEFAULT_BACKEND NGL_BACKEND_METAL
OK, I have reverted back to use OpenGL ES for android and iphone, and OpenGL for others

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    .buffer_freep                       = ngli_buffer_mtl_freep,
For d3d12 here I didn't use the same convention for the ngli part.

Maybe we could status on a common convention.
Like you I prefix some 
`mtl_get_scissor -> d3d12_get_scissor`

And change the rest do get the same prefix on every fonction.

`ngli_buffer_mtl_create -> d3d12_buffer_create`

But it could be 
```
1 - ngli_buffer_mtl_create
2 - ngli_mtl_buffer_create
3 - mtl_ngli_buffer_create
4 - mtl_buffer_create
```

What do you think ?

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    int existing_viewport[4];
Missing a default init

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    float clear_color[4];
Missing a default init
```

    int viewport[4] = { 0,0,0,0 };
    int scissor[4] = { 0,0,0,0 };
    float clear_color[4] = { 0.f,0.f,0.f,0.f };
```

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/graphics_pipeline_mtl.cpp
> +
Maybe add a log is depth_format not found ?

`		LOG(ERROR, "StencilFormat is unknown");`

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/graphics_pipeline_mtl.h
> +    };
Missing some default init

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +};
Missing some default init

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +    bool blend_enable;
Missing default init

2023-08-11 13:55 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +    bool stencil_test_enable;
Missing default init

2023-08-11 14:15 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    .buffer_freep                       = ngli_buffer_mtl_freep,
`mtl_buffer_create ` is I think a convenient way, you can search for all backend easily `_buffer_create`, or limit to only a special backend `mtl_buffer_create`

2023-08-11 15:19 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/pipeline_mtl.cpp
> +                                    int size)
Here something maybe "weird"
`ngli_pipeline_mtl_update_buffer `is the same as `ngli_pipeline_mtl_update_attribute`

`offset` and `size` are not used.
In the d3d12 version they are saved to be reuse when uploading buffer.

2023-08-11 18:28 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +        .max_compute_work_group_invocations = 1024,
In Metal, the max number of threadgroups (work groups) is 1024 according to the Metal Feature Set Table document. The max number of threads in a threadgroup is determined at runtime, usually is 1024 or 512.  For those GPUs we support, they are 1024, only Apple2/3 GPU have 512 limit.  iPhone 6 has Apple 2 GPU, iPhone 7 has Apple 3 GPU.  They are quite old.  I added a comment, if there is a need to support older GPU, I will add.

2023-08-11 18:28 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    bool is_valid;
Added,   Thanks @rlavarec-gpsw

2023-08-11 18:28 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    int height;
Added, Thanks @rlavarec-gpsw

2023-08-11 18:29 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +
Added, Thanks @rlavarec-gpsw

2023-08-11 18:29 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    int default_color_format;
Added, Thanks @rlavarec-gpsw

2023-08-11 18:29 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    if (ctx->device->depth24Stencil8PixelFormatSupported()) {
Can you explain more?

2023-08-11 18:30 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +
I added is_valid = false as default

2023-08-11 18:30 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +
Added, Thanks, @rlavarec-gpsw

2023-08-11 18:31 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    std::memcpy(ctx->viewport, viewport, sizeof(ctx->viewport));
changed per your suggestion

2023-08-11 18:31 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/graphics_pipeline_mtl.h
> +    };
Changed

2023-08-11 18:31 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +};
added

2023-08-11 18:31 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +    bool blend_enable;
added

2023-08-11 18:31 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/graphics_state_mtl.h
> +    bool stencil_test_enable;
added

2023-08-11 18:32 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/pipeline_mtl.cpp
> +
added

2023-08-11 18:32 UTC, wmacdonald-gpsw approved these changes

2023-08-11 18:39 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/pipeline_mtl.cpp
> +                                    int size)
hmm, metal does not them.  during each draw, binding attribute buffer and constant buffer does not require these parameters

2023-08-14 09:00 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +        .max_compute_work_group_invocations = 1024,
Ok nice, Thanks

2023-08-14 09:07 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    if (ctx->device->depth24Stencil8PixelFormatSupported()) {
Yes sorry, maybe it is normal,

But if TARGET_DARWIN is not defined,
mtl_get_preferred_depth_format will return NGLI_FORMAT_D24_UNORM_S8_UINT if ctx not valid, and mtl_get_preferred_depth_stencil_format will return NGLI_FORMAT_D32_SFLOAT_S8_UINT in any case (ctx valid or not valid). Maybe it is the way attended or not. it is not symmetrical, but maybe it is not mean to be.

2023-08-14 09:08 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +static void mtl_set_scissor(struct gpu_ctx *s, const int *scissor);
Ok

2023-08-14 12:51 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    ctx->is_valid = true;
is_valid = true must be set early, other methods depend on it too.

2023-08-14 13:25 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    if (ctx->device->depth24Stencil8PixelFormatSupported()) {
The way is 
(1) if context is not valid or D24S8 is supported on Mac, D24S8 is the preferred format
(2) otherwise on Mac, or any cases on iPhone,. D32S8 is the preferred format.

This is because on iPhone, only D32S8 is supported, but on Mac, some mac does not support D32S8.

2023-08-14 20:50 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    if (ctx->device->depth24Stencil8PixelFormatSupported()) {
ah,  Yes, you are right.  changed to match each other.  Thanks

2023-08-14 20:53 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/pipeline_mtl.cpp
> +    }
That is good idea.  That would need to change in the frontend as well as in the backend for all backends.  It would be a new JIRA ticket.

2023-08-15 17:01 UTC, jstys-gpsw commented on ngl-tools/wsi_cocoa.m
> +            config->window = (uintptr_t)view;
This could get pulled back out of these blocks to where it was previously, unless you were aiming to make the supported backends more explicit by excluding `NGL_BACKEND_OPENGLES`

2023-08-15 20:55 UTC, hsong-gpsw commented on ngl-tools/wsi_cocoa.m
> +            config->window = (uintptr_t)view;
That is good point, I have reverted it back.  Thanks

2023-08-16 14:53 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/rendertarget_mtl.cpp
> +                                          float clear_depth, float clear_stencil)
detail: you could use uint32_t for the clear_stencil

Because inside metal:
`var clearStencil: [UInt32] { get set }`

2023-08-16 15:20 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/rendertarget_mtl.cpp
> +                                          float clear_depth, float clear_stencil)
with Metal->cpp binding, there is a RenderPassStencilAttachmentsDescriptor::setClearStencil(double) and RenderPassDepthAttachmentsDescriptor::setClearDepth(double).  They are both double.

2023-08-16 15:29 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +    std::smatch m;
Sorry, I misunderstand you.  Changed.  Thank you. @rlavarec-gpsw

2023-08-16 15:34 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/rendertarget_mtl.cpp
> +                                          float clear_depth, float clear_stencil)
Oh ok, sorry

2023-08-16 15:38 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.h
> +    float clear_color[4];
Yes,  Changed,  Thanks @rlavarec-gpsw

2023-08-16 16:09 UTC, mrobertseidowsky-gpsw commented
Hi, thank you for this work!
I think for readability this PR can be splitted into multiple commits which will be atomic:
- cross-compilation files `.github/meson-ios-arm64.ini` and `.github/meson-ios-x86_64.ini` can be introduced in a commit
- version file renaming can be introduced in a commit with its usage in `meson.build`
- c++17 support
- etc
In general, don't you think you can introduce step by step the commit like the necessary tools (all the headers) then the activation of the metal backend?

Also, there are some extra white spaces in the code, it would be nice to have a little cosmetic commit to remove it.
There are also a new blank lines introduced.

2023-08-17 03:38 UTC, wmacdonald-gpsw commented
> Hi, thank you for this work! I think for readability this PR can be splitted into multiple commits which will be atomic:
> 
> * cross-compilation files `.github/meson-ios-arm64.ini` and `.github/meson-ios-x86_64.ini` can be introduced in a commit
> * version file renaming can be introduced in a commit with its usage in `meson.build`
> * c++17 support
> * etc
> 
> In general, don't you think you can introduce step by step the commit like the necessary tools (all the headers) then the activation of the metal backend?
> 
> Also, there are some extra white spaces in the code, it would be nice to have a little cosmetic commit to remove it. There are also a new blank lines introduced.

Hi @mrobertseidowsky-gpsw, it was actually JB who suggested consolidating commits, originally this PR was many individual commits, but JB doesn't see benefit to commits that partially add a completely new backend. I do think it would make sense to break out commits like your examples, which do not directly add the backend code, but prepare build/configuration for it.

@hsong-gpsw can you separate the build and configuration changes, such as c++17 support, updated version file, etc. into their own commits? I think it is ok to leave the new source files for the backend itself as a single commit.

2023-08-17 17:26 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +            flock(lock_fd, LOCK_UN);
Do we need to 
`flock(lock_fd, LOCK_UN); `?

It seems the lock is done inside generate_shader_from_glsl_data

2023-08-17 17:26 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +            flock(lock_fd, LOCK_UN);
Do we need to 
`flock(lock_fd, LOCK_UN); `?

It seems the lock is done inside generate_shader_from_glsl_data

2023-08-17 17:29 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +    uint32_t height;
added,  Thank you

2023-08-17 17:37 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +}
OK, I added a log

2023-08-17 17:40 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +            flock(lock_fd, LOCK_UN);
Nice catch, it is not needed here,  I have removed it.

2023-08-17 17:41 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +            flock(lock_fd, LOCK_UN);
Right, same as above, nice catch,  I have removed it.  This part of code was copied from generate_shader_from_glsl_data()

2023-08-17 17:44 UTC, hsong-gpsw commented
@mrobertseidowsky-gpsw and @wmacdonald-gpsw I have separated the commit into two commits, one  contains backend source codes and the second one contains build script changes.  Thank you for your suggestions.

2023-08-17 17:45 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +        return false;
Yes, nice catch,  I have fixed it.

2023-08-17 17:48 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.cpp
> +        pool->release();
Yes, nice catch,  I have fixed it.  Thank you

2023-08-18 09:01 UTC, rlavarec-gpsw approved these changes

2023-08-18 09:24 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        struct texture_mtl *msaa_texture;
Missing some default init

2023-08-18 09:24 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        MTL::LoadAction load_op;
Missing some default init

2023-08-18 09:24 UTC, rlavarec-gpsw commented on .github/meson-ios-x86_64.ini
> +cpp = 'clang++'
I added this line 2 days ago in the main if you rebase.

2023-08-18 09:31 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    const uint8_t buf[4] = { 0 };
Why not ?
`const uint8_t buf[4] = { 0,0,0,0 };`

2023-08-18 09:54 UTC, rlavarec-gpsw commented on libnodegl/src/backends/metal/shader_mtl.h
> +    int lock_fd;
Missing some default init

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/shader_mtl.h
> +    int lock_fd;
I have added

2023-08-18 13:55 UTC, hsong-gpsw commented on .github/meson-ios-x86_64.ini
> +cpp = 'clang++'
Yes, I saw that.

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/gpu_ctx_mtl.cpp
> +    const uint8_t buf[4] = { 0 };
Yes, I have added

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        MTL::LoadAction load_op;
yes, I have added

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/framebuffer_mtl.h
> +        struct texture_mtl *msaa_texture;
Yes, I have added

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/texture_mtl.cpp
> +#endif
Yes, I have changed.  Thank you

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/texture_mtl.cpp
> +    }
Yes, I have changed.  Thank you

2023-08-18 13:55 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/texture_mtl.cpp
> +        priv->bytes_per_pixel = ngli_format_get_bytes_per_pixel(stencil_format);
Yes, great,  I have changed according to your suggestions.  Thank you

2023-08-18 13:56 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/surface_mtl.h
> +    MTL::PixelFormat default_depth_stencil_format;
Yes, I have added.

2023-08-18 13:56 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/surface_mtl.h
> +    uint32_t height;
Yes, I have added

2023-08-18 13:56 UTC, hsong-gpsw commented on libnodegl/src/backends/metal/surface_mtl.cpp
> +#endif
Yes, great,  I have changed that.  Thank you @rlavarec-gpsw

2023-08-18 13:57 UTC, hsong-gpsw commented on .github/meson-ios-x86_64.ini
> +cpp = 'clang++'
It will be resolved when merging

2023-08-18 16:20 UTC, wmacdonald-gpsw commented on libnodegl/meson.build
> +    lib_src += files('src/gpu_capture_metal.m')
move back to other commit

2023-08-18 16:21 UTC, wmacdonald-gpsw commented on libnodegl/meson.build
> +  },
move back to other commit

2023-08-18 16:21 UTC, wmacdonald-gpsw commented on libnodegl/meson_options.txt
> +option('debug_opts', type: 'array', choices: ['gl', 'vk', 'mtl', 'mem', 'scene', 'gpu_capture'], value: [],
move back to other commit

2023-08-18 17:44 UTC, hsong-gpsw commented on libnodegl/meson.build
> +conf_data.set10('DEBUG_MTL', 'mtl' in debug_opts)
OK, I have restructured commits.  Please check

2023-08-18 17:44 UTC, hsong-gpsw commented on libnodegl/meson.build
> +    lib_src += files('src/gpu_capture_metal.m')
I have re-structured commits.  Please review

2023-08-18 17:44 UTC, hsong-gpsw commented on libnodegl/meson.build
> +  },
I have re-structured commits.  Please review

2023-08-18 17:44 UTC, hsong-gpsw commented on libnodegl/meson_options.txt
> +option('gbackend-mtl', type: 'feature', value: 'auto')
I have restructured commits.  Please review

2023-08-18 17:44 UTC, hsong-gpsw commented on libnodegl/meson_options.txt
> +option('debug_opts', type: 'array', choices: ['gl', 'vk', 'mtl', 'mem', 'scene', 'gpu_capture'], value: [],
I have restructured commits, please review

2023-08-21 23:12 UTC, merged